"""Growth / launch checklist (assets/consent.js, ab.js, reviews.js, info.js + the app.js / pages.js / legal.js hooks):

  licenses page   #licenses + /licenses: every component group, copyleft notices + source links + local license files,
                  external links open safely; footer links on home / tool / pricing; 5 languages, he/ar RTL, dark, 375 px
  accessibility   #accessibility + /accessibility: all statement sections (status, adjustments, alternatives, limitations,
                  how checked, physical, coordinator, handling, last update), no "[placeholder]" for visitors, a warning only
                  for admins, #about-a11y redirects, the a11y panel links to it, "open the menu" button
  consent         no ids → no banner and no GA/Clarity request even with a saved yes; ids → banner, still no request until
                  "allow"; "necessary only" → nothing loads (also after reload); "allow" → gtag.js + clarity tag with the
                  configured ids, Google signals / ad personalisation off, page_view per view change (virtual path, no
                  query/hash), key events from logAct without song names, sign_up, inputs + song name masked for Clarity;
                  cookie settings dialog (focus, Esc, switch) withdraws → ga-disable + no more events; invalid ids never
                  load; Search Console meta from the config; zero CSP violations
  A/B             off by default (control, nothing stored or logged), on → sticky variant, hero text/data-ab follow it,
                  one ab_assign per member, GA user property with consent; admin Growth tab: id validation, add the
                  shipped experiment, enable + save, results table
  reviews         prompt after 3 exports (dismissible, not again within 30 days), dialog (stars radio group, Esc + focus
                  return, rating required, links / offensive refused, not-eligible message), admin approve + feature,
                  home shows approved reviews only (initials unless opted in) + average, payloads stay text, JSON-LD only
                  with ≥ 5 reviews, en/ar dialog, dark 375 px
  paths & SEO     /pricing /terms /privacy /tool /accessibility /licenses → their view, canonical + og:url per page, the
                  path kept until the user navigates (then /#view), unknown path → home + notice; crawler UAs
                  (facebookexternalhit/1.1, WhatsApp/2.23) get 200 HTML with the OG tags directly, og.png served
  referral        disclosure in the invite card + the shared message says the inviter gets points
"""
import os, sys, re, json, time, urllib.request, urllib.parse
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
import lib

IDS = "__mock.setCfg({analytics:{ga4:'G-TEST1234',clarity:'abc123xyz',gsc:'abcdefghij_KLMNOP-123'}});"
EXP_ON = "__mock.setCfg({experiments:[{id:'home_cta',on:true,variants:['a','b'],conversion:'song_upload',note:'x'}]});"
STUB_HOSTS = re.compile(r'^https://([a-z0-9-]+\.)*(googletagmanager\.com|google-analytics\.com|analytics\.google\.com|clarity\.ms|c\.bing\.com)/.*')

def ctx_with_stubs(b, srv, t, **kw):
    """context whose analytics hosts are answered by a stub (and recorded) instead of being aborted"""
    ctx, pg = lib.page(b, srv, t, init=lib.CSP_INIT, **kw)
    seen = []
    def stub(r):
        seen.append(r.request.url)
        r.fulfill(status=200, content_type='text/javascript', body='window.__stub=(window.__stub||0)+1;', headers={'access-control-allow-origin': '*'})
    ctx.route(STUB_HOSTS, stub)
    return ctx, pg, seen

def dl(pg): return pg.evaluate("JSON.stringify((window.dataLayer||[]).map(a=>Array.from(a)))")
def visible(pg, sel): return pg.evaluate("s=>{const e=document.querySelector(s);return !!e&&!e.hidden&&e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden'}", sel)

@lib.main
def test(t, srv, b):
    # ------------------------------------------------------------------ licenses + accessibility pages
    t.section('licenses page')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='he', theme='light', init=lib.CSP_INIT)
    pg.goto(srv.url('#licenses')); lib.wait_booted(pg)
    t.eq('#licenses → the info view', lib.visible_views(pg), ['#infoView'])
    t.eq('h1', pg.inner_text('#infoH').strip(), 'רישיונות וקרדיטים')
    t.check('title per page', pg.title().startswith('רישיונות וקרדיטים ·'), pg.title())
    for sec in ['lic-fonts', 'lic-icons', 'lic-libs', 'lic-models', 'lic-data', 'lic-source', 'lic-tm', 'lic-texts']:
        t.check(f'section #{sec}', pg.query_selector('#infoView #' + sec) is not None)
    txt = pg.inner_text('#infoView')
    for w in ['IBM Plex', 'Atkinson Hyperlegible', 'SIL OFL 1.1', 'supabase-js', 'Signalsmith Stretch', 'ONNX Runtime Web', 'demucs-js',
              'lamejs', 'LGPL-3.0', 'ffmpeg.wasm', 'GPL-2.0-or-later', 'HTDemucs', 'Deezer', 'Google Analytics 4', 'Microsoft Clarity', '1.2.7', '0.12.10', '2.117.2']:
        t.check(f'lists {w}', w in txt)
    t.check('model weights: honest "not MIT / research" note', 'מחקרי' in txt and 'MIT' in txt)
    t.check('local license files linked (lamejs, ffmpeg)', pg.query_selector('#infoView a[href="vendor/lamejs-1.2.7.LICENSE.txt"]') is not None and pg.query_selector('#infoView a[href="vendor/ffmpeg/LICENSE.txt"]') is not None)
    t.check('source links for the copyleft parts', pg.query_selector('#infoView a[href*="shijinyu/lamejs/tree/"]') is not None and pg.query_selector('#infoView a[href*="@ffmpeg/core/v/0.12.10"]') is not None)
    t.check('written offer for the source', 'שלוש שנים' in txt)
    t.check('every external link: target _blank + rel noopener', pg.evaluate("[...document.querySelectorAll('#infoView a[href^=\"http\"]')].every(a=>a.target==='_blank'&&/noopener/.test(a.rel))"))
    t.check('MIT text in a <details>', 'Permission is hereby granted' in pg.evaluate("document.querySelector('#infoView .lic-txt pre').textContent"))
    for lang, h in [('en', 'Licenses & credits'), ('ar', 'التراخيص والشكر'), ('ru', 'Лицензии и благодарности'), ('es', 'Licencias y créditos')]:
        pg.select_option('#lang', lang); time.sleep(0.4)
        t.eq(f'{lang}: h1', pg.inner_text('#infoH').strip(), h)
        if lang == 'ar': t.eq('ar: RTL', pg.evaluate('document.documentElement.dir'), 'rtl')
    pg.select_option('#lang', 'he'); time.sleep(0.3)
    t.section('accessibility page')
    pg.evaluate("location.hash='#about-a11y'"); time.sleep(0.8)
    t.check('#about-a11y redirects to #accessibility', lib.visible_views(pg) == ['#infoView'] and pg.evaluate('location.hash') == '#accessibility', pg.evaluate('location.hash'))
    for sid in ['a11y-status', 'a11y-menu', 'a11y-adj', 'a11y-alt', 'a11y-lim', 'a11y-test', 'a11y-phys', 'a11y-contact']:
        t.check(f'statement section #{sid}', pg.query_selector('#infoView #' + sid) is not None)
    a11 = pg.inner_text('#infoView')
    t.check('compliance level: IS 5568 AA + WCAG', '5568' in a11 and 'AA' in a11 and 'WCAG 2.0' in a11 and 'WCAG 2.1' in a11)
    t.check('law + regulations 2013 cited', 'התשע"ג-2013' in a11)
    t.check('last update date shown (no placeholder)', 'ההצהרה עודכנה לאחרונה' in a11 and '2026' in a11 and '[תאריך]' not in a11)
    t.check('visitors see no "[placeholder]" and no admin warning', '[' not in a11 and pg.query_selector('#infoView .a11y-warn') is None)
    pg.click('#infoView [data-a11y-open]'); time.sleep(0.4)
    t.check('"open the accessibility menu" button opens the panel', pg.evaluate("!!document.querySelector('.a11y-panel')&&!document.querySelector('.a11y-panel').hidden"))
    pg.keyboard.press('Escape'); time.sleep(0.3)
    t.check('the a11y panel links to the statement page', pg.query_selector('.a11y-link[href="#accessibility"]') is not None)
    lib.sign_up(pg, 'oshri', 'o@x.com'); time.sleep(0.6)
    t.check('admin: warning that the coordinator is not filled in', pg.query_selector('#infoView .a11y-warn') is not None)
    lib.sign_out(pg)
    pg.evaluate("location.hash=''"); time.sleep(0.8)
    foot = pg.evaluate("[...document.querySelectorAll('#aboutView .pg-legal a')].map(a=>a.getAttribute('href'))")
    t.check('home footer: terms, privacy, accessibility, licenses', all(x in foot for x in ['#terms', '#privacy', '#accessibility', '#licenses']), foot)
    t.check('home footer: cookie settings button', pg.query_selector('#aboutView .pg-legal [data-ck="open"]') is not None)
    t.check('tool footer: accessibility + licenses + cookie settings', pg.evaluate("['#accessibility','#licenses'].every(h=>document.querySelector('#toolView .flegal a[href=\"'+h+'\"]'))&&!!document.querySelector('#toolView .flegal [data-ck=open]')"))
    t.check('About keeps a short a11y teaser linking to the full statement', pg.query_selector('#about-a11y a[href="#accessibility"]') is not None)
    t.eq('CSP: no violations on the pages', lib.csp_violations(pg), [])
    ctx.close()
    for lang, theme in [('he', 'dark'), ('ar', 'dark'), ('en', 'light')]:
        ctx, pg = lib.page(b, srv, t, mock=True, lang=lang, theme=theme, w=375, h=780, mobile=True)
        for h in ['#licenses', '#accessibility']:
            pg.goto(srv.url(h)); lib.wait_booted(pg); time.sleep(0.6)
            t.check(f'{lang}/{theme} 375 {h}: no horizontal scroll', lib.scroll_width(pg) <= 375, lib.scroll_width(pg))
            if theme == 'dark': t.check(f'{lang} dark {h}: dark page', lib.page_luma(pg, '#infoView .lg-doc') < 60)
            t.shot(pg, f'{h[1:]}_{lang}_{theme}_375', full_page=True)
        t.eq(f'{lang}: dir', pg.evaluate('document.documentElement.dir'), 'rtl' if lang in ('he', 'ar') else 'ltr')
        ctx.close()

    # ------------------------------------------------------------------ paths, canonical, crawlers
    t.section('real paths + per-page canonical')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='he', init=lib.CSP_INIT)
    for path, view in [('pricing', '#pricingView'), ('terms', '#legalView'), ('privacy', '#legalView'), ('accessibility', '#infoView'), ('licenses', '#infoView')]:
        pg.goto(srv.url(path)); lib.wait_booted(pg); time.sleep(0.5)
        t.check(f'/{path} → {view}', lib.visible_views(pg) == [view], lib.visible_views(pg))
        t.eq(f'/{path}: URL keeps the path', pg.evaluate('location.pathname+location.hash'), '/' + path)
        t.eq(f'/{path}: canonical', pg.evaluate("document.querySelector('link[rel=canonical]').href"), 'https://chord-room.pages.dev/' + path)
        t.eq(f'/{path}: og:url', pg.evaluate("document.querySelector('meta[property=\"og:url\"]').content"), 'https://chord-room.pages.dev/' + path)
    pg.goto(srv.url('privacy')); lib.wait_booted(pg); time.sleep(0.5)
    t.check('privacy policy: cookies/analytics + reviews sections', pg.query_selector('#legalView #p-cookies') is not None and pg.query_selector('#legalView #p-reviews') is not None)
    pt = pg.inner_text('#legalView')
    t.check('privacy names GA4 + Clarity and consent', 'Google Analytics 4' in pt and 'Microsoft Clarity' in pt and 'הגדרות עוגיות' in pt)
    t.check('privacy no longer claims "no third-party analytics"', 'באנליטיקה של צד שלישי' not in pt)
    pg.goto(srv.url('terms')); lib.wait_booted(pg); time.sleep(0.5)
    t.check('terms: reviews + invite-program sections', pg.query_selector('#legalView #t-reviews') is not None and pg.query_selector('#legalView #t-referral') is not None)
    pg.goto(srv.url('pricing')); lib.wait_booted(pg); time.sleep(0.5)
    pg.click('#navAbout'); time.sleep(0.5)
    t.eq('leaving the path page → back to /', pg.evaluate('location.pathname+location.hash'), '/')
    t.eq('home canonical', pg.evaluate("document.querySelector('link[rel=canonical]').href"), 'https://chord-room.pages.dev/')
    pg.click('#navPricing'); time.sleep(0.5)
    t.eq('in-app navigation still uses hashes', pg.evaluate('location.hash'), '#pricing')
    t.eq('…canonical is the clean path', pg.evaluate("document.querySelector('link[rel=canonical]').href"), 'https://chord-room.pages.dev/pricing')
    pg.goto(srv.url('no-such-page')); lib.wait_booted(pg); time.sleep(1)
    t.check('unknown path → home + notice', lib.visible_views(pg) == ['#aboutView'] and not pg.evaluate("document.querySelector('#toast').hidden"))
    pg.goto(srv.url('accessibility') + '#terms'); lib.wait_booted(pg); time.sleep(0.5)
    t.check('a hash wins over the path', lib.visible_views(pg) == ['#legalView'])
    pg.goto(srv.url('pricing')); lib.wait_booted(pg); time.sleep(0.5)
    pg.select_option('#lang', 'en'); time.sleep(0.4)
    t.check('og:description follows the language', 'free' in pg.evaluate("document.querySelector('meta[property=\"og:description\"]').content"))
    t.eq('CSP: none on the path pages', lib.csp_violations(pg), [])
    ctx.close()
    t.section('crawlers (link previews)')
    for ua in ['facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)', 'WhatsApp/2.23.20.0 A']:
        for path in ['', 'pricing']:
            req = urllib.request.Request(srv.url(path), headers={'User-Agent': ua})
            with urllib.request.urlopen(req) as r:
                body = r.read().decode('utf-8'); final = r.geturl(); ct = r.headers.get('content-type')
            t.check(f'{ua.split("/")[0]} /{path}: 200 HTML, no redirect', r.status == 200 and final == srv.url(path) and 'text/html' in ct, (r.status, final))
            og = dict(re.findall(r'<meta property="(og:[a-z:_]+)" content="([^"]*)"', body))
            t.check(f'{ua.split("/")[0]} /{path}: og:title/description/image/url present, image absolute https',
                    all(k in og for k in ['og:title', 'og:description', 'og:image', 'og:url', 'og:image:width', 'og:image:height', 'og:image:type']) and og['og:image'].startswith('https://'), list(og)[:6])
        req = urllib.request.Request(srv.url('assets/og.png'), headers={'User-Agent': ua})
        with urllib.request.urlopen(req) as r:
            data = r.read()
        t.check(f'{ua.split("/")[0]}: og.png 200, PNG ≤ 300 KB (CORP: node/growth.test.mjs)', r.status == 200 and data[1:4] == b'PNG' and len(data) <= 300 * 1024, len(data))

    # ------------------------------------------------------------------ consent + analytics
    t.section('consent: no ids → no banner, nothing loads')
    ctx, pg, seen = ctx_with_stubs(b, srv, t, mock=True, lang='he')
    ctx.add_init_script("try{localStorage.setItem('chordroom.consent.v1',JSON.stringify({v:1,a:true,at:'2026-01-01'}))}catch(e){}")
    pg.goto(srv.url()); lib.wait_booted(pg); time.sleep(2)
    t.check('no banner without ids', pg.query_selector('#ckBar') is None or not visible(pg, '#ckBar'))
    t.eq('no analytics request without ids (even with a saved yes)', seen, [])
    pg.click('#aboutView .pg-legal [data-ck="open"]'); time.sleep(0.4)
    t.check('cookie settings dialog still opens + says analytics is not active', visible(pg, '#ckDlg') and 'לא מופעלים' in pg.inner_text('#ckDlg'))
    pg.keyboard.press('Escape'); time.sleep(0.2)
    ctx.close()

    t.section('consent: ids set → banner, opt-in only')
    ctx, pg, seen = ctx_with_stubs(b, srv, t, mock=lib.mock_js(IDS), lang='he')
    pg.goto(srv.url()); lib.wait_booted(pg); time.sleep(1.5)
    t.check('banner shown (region, Hebrew)', visible(pg, '#ckBar') and pg.get_attribute('#ckBar', 'role') == 'region' and 'עוגיות' in pg.inner_text('#ckBar'))
    t.check('accept and reject equally prominent (both solid buttons)', pg.evaluate("['all','none'].every(k=>document.querySelector('#ckBar [data-ck='+k+']').classList.contains('solid'))"))
    t.eq('no GA / Clarity request before consent', seen, [])
    t.check('Search Console meta from the config', pg.evaluate("document.querySelector('meta[name=google-site-verification]').content") == 'abcdefghij_KLMNOP-123')
    t.check('the a11y button is lifted above the banner', pg.evaluate("(()=>{const f=document.querySelector('.a11y-fab').getBoundingClientRect(),b=document.querySelector('#ckBar .ck-in').getBoundingClientRect();return f.bottom<=b.top+1||f.top>=b.bottom})()"))
    t.shot(pg, 'consent_banner_he')
    pg.click('#ckBar [data-ck="none"]'); time.sleep(1.5)
    t.check('"necessary only" → banner gone, choice saved', not visible(pg, '#ckBar') and pg.evaluate("JSON.parse(localStorage.getItem('chordroom.consent.v1')).a") is False)
    t.eq('…and nothing loaded', seen, [])
    lib.reload(pg); time.sleep(1.5)
    t.check('after reload: no banner, nothing loaded', (pg.query_selector('#ckBar') is None or not visible(pg, '#ckBar')) and seen == [], seen)
    ctx.close()

    t.section('consent: allow → GA4 + Clarity')
    ctx, pg, seen = ctx_with_stubs(b, srv, t, mock=lib.mock_js(IDS), lang='he')
    pg.goto(srv.url()); lib.wait_booted(pg); time.sleep(1.2)
    pg.click('#ckBar [data-ck="all"]'); time.sleep(1.2)
    t.check('gtag.js loaded with the configured id', any('www.googletagmanager.com/gtag/js?id=G-TEST1234' in u for u in seen), seen)
    t.check('Clarity tag loaded with the configured id', any(u.startswith('https://www.clarity.ms/tag/abc123xyz') for u in seen), seen)
    d = dl(pg)
    t.check('GA config: no page_view by itself, Google signals + ad personalisation off', '"send_page_view":false' in d and '"allow_google_signals":false' in d and '"allow_ad_personalization_signals":false' in d, d[:300])
    t.check('consent mode: ads denied, analytics granted', '"ad_storage":"denied"' in d and '"analytics_storage":"granted"' in d)
    t.check('page_view for the current view (virtual path "/")', '"page_view",{"page_location":"' in d and '"page_path":"/"' in d)
    pg.click('#navPricing'); time.sleep(0.6)
    d = dl(pg)
    t.check('page_view on view change (/pricing, no hash/query)', '"page_path":"/pricing"' in d and '#' not in json.dumps([x for x in json.loads(d) if x[0] == 'event']))
    lib.sign_up(pg, 'oshri', 'o@x.com')
    pg.evaluate("CR.log('export','My Secret Song.wav');CR.log('separate','Another Name.mp3');document.dispatchEvent(new CustomEvent('cr-signup'))"); time.sleep(0.3)
    d = dl(pg)
    t.check('key events: export, separation, sign_up', all(f'"event","{e}"' in d for e in ['export', 'separation', 'sign_up']), d[-300:])
    t.check('no song names / emails in anything sent to GA', 'Secret Song' not in d and 'Another Name' not in d and 'o@x.com' not in d and 'oshri' not in d)
    t.check('Clarity: inputs + song name + account areas masked', pg.evaluate("['#tname','#acc','#admin'].every(s=>document.querySelector(s).getAttribute('data-clarity-mask')==='true')&&[...document.querySelectorAll('input')].every(i=>i.getAttribute('data-clarity-mask')==='true')"))
    pg.evaluate("document.body.insertAdjacentHTML('beforeend','<input id=lateInput>')"); time.sleep(0.2)
    t.check('Clarity: inputs added later are masked too', pg.get_attribute('#lateInput', 'data-clarity-mask') == 'true')
    pg.evaluate("document.querySelector('[data-ck=open]').click()"); time.sleep(0.4)
    t.check('settings dialog: focus on the switch, switch is on', pg.evaluate("document.activeElement&&document.activeElement.id")=='ckAn' and pg.get_attribute('#ckAn', 'aria-checked') == 'true')
    pg.keyboard.press('Space'); time.sleep(0.1)
    t.eq('switch toggles with the keyboard', pg.get_attribute('#ckAn', 'aria-checked'), 'false')
    pg.click('#ckDlg [data-ck="save"]'); time.sleep(0.3)
    n0 = len(dl(pg))
    pg.evaluate("CR.log('export','x2')"); pg.click('#navAbout'); time.sleep(0.5)
    t.check('withdrawn: ga-disable set, choice saved false, no more events', pg.evaluate("window['ga-disable-G-TEST1234']===true&&JSON.parse(localStorage.getItem('chordroom.consent.v1')).a===false") and len(dl(pg)) == n0)
    t.eq('CSP: no violations with analytics loaded', lib.csp_violations(pg), [])
    ctx.close()
    ctx, pg, seen = ctx_with_stubs(b, srv, t, mock=lib.mock_js("__mock.setCfg({analytics:{ga4:'G-<img src=x>',clarity:'javascript:x'}});"), lang='he')
    ctx.add_init_script("try{localStorage.setItem('chordroom.consent.v1',JSON.stringify({v:1,a:true,at:'2026-01-01'}))}catch(e){}")
    pg.goto(srv.url()); lib.wait_booted(pg); time.sleep(1.5)
    t.check('invalid ids: nothing loads, no banner', seen == [] and (pg.query_selector('#ckBar') is None or not visible(pg, '#ckBar')), seen)
    ctx.close()
    for lang, word in [('en', 'Cookies'), ('ar', 'ملفات تعريف'), ('ru', 'Cookie'), ('es', 'Cookies')]:
        ctx, pg, seen = ctx_with_stubs(b, srv, t, mock=lib.mock_js(IDS), lang=lang, theme='dark', w=375, h=780, mobile=True)
        pg.goto(srv.url()); lib.wait_booted(pg); time.sleep(1.2)
        t.check(f'{lang} dark 375: banner text + fits', word in pg.inner_text('#ckBar') and lib.scroll_width(pg) <= 375)
        if lang in ('en', 'ar'): t.shot(pg, f'consent_{lang}_dark_375')
        ctx.close()

    # ------------------------------------------------------------------ A/B
    t.section('A/B: off by default')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='he')
    pg.goto(srv.url()); lib.wait_booted(pg); time.sleep(0.8)
    t.eq('no experiment → control', pg.evaluate("AB.variant('home_cta',['a','b'])"), 'a')
    t.check('hero shows the control text, nothing stored', pg.get_attribute('#aboutView .pg-btn.pri', 'data-ab') == 'home_cta:a' and 'פתחו את הכלי' in pg.inner_text('#aboutView .pg-btn.pri') and pg.evaluate("AB.assignments()") == {})
    lib.sign_up(pg, 'oshri', 'o@x.com'); time.sleep(1.5)
    t.check('…and nothing logged', not pg.evaluate("(window.__log||[]).some(r=>r.action==='ab_assign')"))
    t.section('A/B: admin Growth tab')
    pg.click('#adminBtn'); time.sleep(0.6); pg.click('#admTabs [data-v="growth"]'); time.sleep(0.5)
    t.check('Growth tab visible', visible(pg, '#admGrowth') and pg.query_selector('#gxGa4') is not None)
    pg.fill('#gxGa4', 'UA-1234'); pg.click('#gxSaveA'); time.sleep(0.4)
    t.check('invalid GA4 id refused', 'ga4' in pg.inner_text('#gxMsgA') and pg.evaluate("!(__mock.cfg.analytics&&__mock.cfg.analytics.ga4)"))
    pg.fill('#gxGa4', 'G-ABCD1234'); pg.fill('#gxClarity', 'proj12345'); pg.click('#gxSaveA'); time.sleep(0.4)
    t.eq('valid ids saved', pg.evaluate("__mock.cfg.analytics"), {'ga4': 'G-ABCD1234', 'clarity': 'proj12345', 'gsc': ''})
    time.sleep(0.4)
    t.check('ids live → the consent banner appears right away', visible(pg, '#ckBar'))
    pg.click('#ckBar [data-ck="none"]'); time.sleep(0.3)
    pg.click('#admGrowth [data-add="home_cta"]'); time.sleep(0.3)
    t.check('shipped experiment added, off', pg.evaluate("!document.querySelector('#admGrowth .gx-ex [data-k=on]').checked"))
    pg.check('#admGrowth .gx-ex [data-k=on]'); pg.click('#gxSaveE'); time.sleep(0.4)
    t.check('enabled + saved to the config', pg.evaluate("__mock.cfg.experiments[0].id==='home_cta'&&__mock.cfg.experiments[0].on===true&&__mock.cfg.experiments[0].conversion==='song_upload'"))
    pg.evaluate("window.__log.push({user_id:'x1',action:'ab_assign',detail:'home_cta:a'},{user_id:'x1',action:'song_upload',detail:'s'},{user_id:'x2',action:'ab_assign',detail:'home_cta:b'})")
    pg.click('#admGrowth .gx-ex [data-a="res"]'); time.sleep(0.5)
    rows = pg.evaluate("[...document.querySelectorAll('#admGrowth .gx-res tbody tr')].map(r=>[...r.cells].map(c=>c.textContent.trim()))")
    t.check('results table: per variant assigned / converted / rate (x1 converted, x2 not)', len(rows) == 2 and rows[1] == ['b', '1', '0', '0%'] and rows[0][0] == 'a' and rows[0][2] == '1', rows)
    pg.evaluate("CR.setLang('en',true)"); time.sleep(0.6)
    gt = pg.evaluate("[document.documentElement.lang,(document.querySelector('#gxExH')||{}).textContent]")
    t.check('Growth tab in English', gt[1] == 'A/B experiments', gt)
    pg.select_option('#lang', 'he'); time.sleep(0.2)
    pg.click('#adminClose'); time.sleep(0.3)
    ctx.close()
    t.section('A/B: on → sticky + logged once')
    ctx, pg, seen = ctx_with_stubs(b, srv, t, mock=lib.mock_js(EXP_ON + IDS), lang='he')
    ctx.add_init_script("try{localStorage.setItem('chordroom.consent.v1',JSON.stringify({v:1,a:true,at:'2026-01-01'}))}catch(e){}")
    pg.goto(srv.url()); lib.wait_booted(pg); time.sleep(1.2)
    v = pg.evaluate("AB.assignments().home_cta")
    t.check('assigned a/b and stored', v in ('a', 'b'), v)
    t.check('hero follows the variant', pg.get_attribute('#aboutView .pg-btn.pri', 'data-ab') == 'home_cta:' + v and (('נסו בחינם' in pg.inner_text('#aboutView .pg-btn.pri')) == (v == 'b')))
    lib.reload(pg); time.sleep(1)
    t.eq('sticky across reloads', pg.evaluate("AB.assignments().home_cta"), v)
    t.check('GA user property ab_home_cta with consent', f'"ab_home_cta":"{v}"' in dl(pg), dl(pg)[:300])
    pg.evaluate("localStorage.setItem('chordroom.ab.v1',JSON.stringify({home_cta:'b'}))"); lib.reload(pg); time.sleep(1)
    t.check('variant b → "נסו בחינם, בלי התקנה"', 'נסו בחינם, בלי התקנה' in pg.inner_text('#aboutView .pg-btn.pri'))
    lib.sign_up(pg, 'oshri', 'o@x.com'); time.sleep(1.8)
    pg.evaluate("location.hash='#pricing'"); time.sleep(0.4); pg.evaluate("location.hash=''"); time.sleep(1.5)
    t.eq('one ab_assign row for the member', pg.evaluate("(window.__log||[]).filter(r=>r.action==='ab_assign').map(r=>r.detail)"), ['home_cta:b'])
    pg.evaluate("(()=>{const e=[{id:'home_cta',on:false,variants:['a','b']}];__mock.setCfg({experiments:e});CR.ACC.config={...CR.ACC.config,experiments:e};document.dispatchEvent(new CustomEvent('cr-config'))})()"); time.sleep(0.8)
    t.check('switched off → control again even with a stored b', 'פתחו את הכלי' in pg.inner_text('#aboutView .pg-btn.pri'))
    t.eq('CSP: none (A/B)', lib.csp_violations(pg), [])
    ctx.close()

    # ------------------------------------------------------------------ reviews
    t.section('reviews: prompt after 3 exports')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='he', init=lib.CSP_INIT)
    pg.goto(srv.url()); lib.wait_booted(pg); time.sleep(0.6)
    t.check('home: no reviews section while none is approved (never invented)', pg.query_selector('#pgReviews') is None and pg.query_selector('#ldRating') is None)
    lib.sign_in(pg)   # dana (plain member)
    pg.evaluate("CR.log('export','a.wav');CR.log('export','b.wav')"); time.sleep(2)
    t.check('2 exports → no prompt yet', pg.query_selector('#rvAsk') is None)
    pg.evaluate("CR.log('mashup_export','c')"); time.sleep(2.2)
    t.check('3rd export → prompt card', visible(pg, '#rvAsk') and 'ביקורת' in pg.inner_text('#rvAsk'))
    t.shot(pg, 'review_prompt')
    pg.click('#rvAsk [data-rv="later"]'); time.sleep(0.3)
    t.check('"not now" hides it', pg.query_selector('#rvAsk') is None)
    pg.evaluate("CR.log('convert','d')"); time.sleep(2.2)
    t.check('not again within 30 days', pg.query_selector('#rvAsk') is None)
    t.section('reviews: dialog')
    pg.evaluate("document.querySelector('#navPricing').focus()")
    pg.evaluate("REVIEWS.open()"); time.sleep(0.5)
    t.check('dialog open, focus on the stars radio group', visible(pg, '#rvDlg') and pg.evaluate("document.activeElement.classList.contains('rv-s')") and pg.get_attribute('#rvDlg .rv-rate', 'role') == 'radiogroup')
    pg.keyboard.press('Escape'); time.sleep(0.3)
    t.check('Esc closes + focus returns', not visible(pg, '#rvDlg') and pg.evaluate("document.activeElement.id") == 'navPricing')
    pg.evaluate("REVIEWS.open()"); time.sleep(0.5)
    pg.click('#rvDlg [data-rv="send"]'); time.sleep(0.2)
    t.check('rating required', 'דירוג' in pg.inner_text('#rvMsg'))
    pg.click('#rvDlg .rv-s[data-n="4"]')
    t.eq('4 stars checked', pg.evaluate("[...document.querySelectorAll('#rvDlg .rv-s')].map(b=>b.getAttribute('aria-checked'))"), ['false', 'false', 'false', 'true', 'false'])
    pg.fill('#rvBody', 'great, see https://spam.example'); pg.click('#rvDlg [data-rv="send"]'); time.sleep(0.4)
    t.check('links refused', 'קישורים' in pg.inner_text('#rvMsg'))
    pg.fill('#rvBody', 'this is shit'); pg.click('#rvDlg [data-rv="send"]'); time.sleep(0.4)
    t.check('offensive refused', 'פוגעניות' in pg.inner_text('#rvMsg'))
    pg.fill('#rvBody', 'מצוין לתרגול <img src=x onerror=window.__pwn=1>')
    t.check('character counter', '/400' in pg.inner_text('#rvCount'))
    pg.click('#rvDlg [data-rv="send"]'); time.sleep(0.5)
    t.check('saved as pending + thanks', not visible(pg, '#rvDlg') and pg.evaluate("__mock.reviews.length===1&&__mock.reviews[0].status==='pending'"))
    lib.sign_out(pg)
    lib.sign_up(pg, 'newbie', 'n@x.com'); time.sleep(0.4)
    pg.evaluate("REVIEWS.open()"); time.sleep(0.5); pg.click('#rvDlg .rv-s[data-n="5"]'); pg.click('#rvDlg [data-rv="send"]'); time.sleep(0.4)
    t.check('member who never used the tools → not eligible', 'אחרי שמשתמשים באתר' in pg.inner_text('#rvMsg'))
    pg.keyboard.press('Escape'); lib.sign_out(pg)
    t.section('reviews: moderation + home')
    lib.sign_up(pg, 'oshri', 'o@x.com'); time.sleep(0.5)
    pg.click('#adminBtn'); time.sleep(0.6); pg.click('#admTabs [data-v="reviews"]'); time.sleep(0.6)
    t.check('Reviews tab lists the pending review (text, not markup)', visible(pg, '#admReviews') and 'מצוין לתרגול <img' in pg.inner_text('#admReviews'))
    pg.click('#admReviews [data-ra="approved"]'); time.sleep(0.4)
    t.check('approved → leaves the pending queue', pg.query_selector('#admReviews .rv-arow') is None)
    pg.select_option('#rvFilter', ''); time.sleep(0.2)
    pg.click('#admReviews [data-ra="feature"]'); time.sleep(0.4)
    t.check('approved + featured', pg.evaluate("__mock.reviews[0].status==='approved'&&__mock.reviews[0].featured===true"))
    pg.click('#adminClose'); time.sleep(0.2)
    pg.evaluate("location.hash=''"); time.sleep(1)
    t.check('home shows the approved review with initials only', visible(pg, '#pgReviews') and 'מצוין לתרגול' in pg.inner_text('#pgReviews') and '— D.' in pg.inner_text('#pgReviews'))
    t.check('the payload stayed text', not pg.evaluate("window.__pwn") and pg.query_selector('#pgReviews img') is None)
    t.check('average shown', '4.0' in pg.inner_text('#pgReviews .rv-sum'))
    t.check('JSON-LD not added with 1 review', pg.query_selector('#ldRating') is None)
    pg.evaluate("""for(let i=0;i<5;i++)__mock.reviews.push({id:10+i,user_id:'u0',rating:5,body:'r'+i,show_name:true,status:'approved',featured:i===0,created_at:new Date().toISOString()});REVIEWS.refresh()"""); time.sleep(0.8)
    ld = pg.evaluate("document.querySelector('#ldRating')&&JSON.parse(document.querySelector('#ldRating').textContent)")
    t.check('JSON-LD AggregateRating with ≥ 5 approved reviews', ld and ld['aggregateRating']['ratingCount'] == 6 and ld['@type'] == 'WebApplication', ld)
    t.check('opted-in name shown', 'Dana' in pg.inner_text('#pgReviews'))
    t.eq('CSP: no violations (JSON-LD data block included)', lib.csp_violations(pg), [])
    for lang, word in [('en', 'What members say'), ('ar', 'ماذا يقول الأعضاء')]:
        pg.select_option('#lang', lang); time.sleep(0.4)
        t.check(f'{lang}: home reviews heading', word in pg.inner_text('#pgReviews'))
    ctx.close()
    for lang, theme in [('ar', 'dark'), ('en', 'light')]:
        ctx, pg = lib.page(b, srv, t, mock=True, lang=lang, theme=theme, w=375, h=780, mobile=True)
        pg.goto(srv.url()); lib.wait_booted(pg); lib.sign_in(pg)
        pg.evaluate("CR.log('export','a')"); pg.evaluate("REVIEWS.open()"); time.sleep(0.6)
        t.check(f'{lang}/{theme} 375: review dialog fits, translated', visible(pg, '#rvDlg') and lib.scroll_width(pg) <= 375 and (('تقييمك' in pg.inner_text('#rvDlg')) if lang == 'ar' else ('Your review' in pg.inner_text('#rvDlg'))))
        t.shot(pg, f'review_dialog_{lang}_{theme}_375')
        ctx.close()

    # ------------------------------------------------------------------ referral disclosure
    t.section('referral disclosure')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='he')
    pg.goto(srv.url('#pricing')); lib.wait_booted(pg); lib.sign_in(pg); time.sleep(1.2)
    pg.evaluate("location.hash='#pricing'"); time.sleep(1)
    disc = pg.evaluate("(document.querySelector('#refCard .refdisc')||{}).textContent||''")
    t.check('invite card carries the disclosure', 'גילוי נאות' in disc, disc)
    wa = pg.evaluate("(document.querySelector('#refCard .refwa')||{}).href||''")
    t.check('the shared WhatsApp message says the inviter gets points', 'מקבל' in urllib.parse.unquote(wa), wa[:120])
    ctx.close()

