"""Sign-up dialog (mock backend with e-mail codes): header buttons, username availability, e-mail/password
validation + strength, caps-lock hint, show-password eye, terms step with required consents (LEGAL.version sent),
6-digit code step (wrong code, resend cooldown, paste), welcome state, signed-in header. Then with confirmation
off: straight to welcome; admin details show the terms version/date."""
import os, sys, time
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import lib

@lib.main
def test(t, srv, b):
    ctx, pg = lib.page(b, srv, t, mock=lib.auth_mock(), h=960, lang='he')
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    t.check('header: sign-in + sign-up buttons', pg.is_visible('#signInBtn') and pg.is_visible('#signUpBtn'))
    pg.click('#signUpBtn'); time.sleep(0.5)
    t.eq('focus on username', pg.evaluate("document.activeElement.id"), 'upUser')
    pg.type('#upUser', 'dana_beats'); time.sleep(0.8)
    t.check('taken username', 'תפוס' in pg.inner_text('#upUserS'), pg.inner_text('#upUserS'))
    pg.fill('#upUser', ''); pg.type('#upUser', 'new_dj'); time.sleep(0.8)
    t.check('free username', 'פנוי' in pg.inner_text('#upUserS'), pg.inner_text('#upUserS'))
    pg.type('#upEmail', 'bad@'); pg.click('#upPass'); time.sleep(0.2)
    t.check('e-mail format error', pg.is_visible('#upEmailE') and pg.inner_text('#upEmailE') != '', pg.inner_text('#upEmailE'))
    pg.fill('#upEmail', 'new@x.com')
    pg.type('#upPass', 'abc'); t.check('short password hint mentions 8', '8' in pg.inner_text('#upPassS'), pg.inner_text('#upPassS'))
    pg.fill('#upPass', ''); pg.type('#upPass', 'Sunset-Groove-2026')
    t.check('strength meter level set', (pg.get_attribute('#upPassM', 'data-l') or '') not in ('', '0'), pg.inner_text('#upPassS'))
    pg.type('#upPass2', 'Sunset-Groove-202'); t.check('mismatch shown', 'תואמות' in pg.inner_text('#upPass2E'), pg.inner_text('#upPass2E'))
    pg.type('#upPass2', '6'); t.check('match shown', pg.inner_text('#upPass2E').startswith('הסיסמאות תואמות'), pg.inner_text('#upPass2E'))
    pg.evaluate("document.getElementById('upPass').dispatchEvent(new KeyboardEvent('keydown',{key:'A',modifierCapsLock:true,bubbles:true}))"); time.sleep(0.1)
    t.check('caps lock hint', pg.is_visible('#upPassCaps'))
    pg.evaluate("document.getElementById('upPass').dispatchEvent(new KeyboardEvent('keyup',{key:'A',bubbles:true}))")
    pg.click('[data-eye=upPass]'); t.eq('eye shows the password', pg.get_attribute('#upPass', 'type'), 'text'); pg.click('[data-eye=upPass]')
    t.shot(pg, 's1_details')
    pg.keyboard.press('Enter'); time.sleep(0.6)
    t.check('terms step', pg.is_visible('#fTerms'))
    t.check('create disabled until consent', pg.is_disabled('#auCreate'))
    pg.click('label.au-chk:has(#auAgree)'); t.check('still disabled with one box', pg.is_disabled('#auCreate'))
    pg.click('label.au-chk:has(#auAge)'); t.check('enabled with both boxes', not pg.is_disabled('#auCreate'))
    t.shot(pg, 's2_terms')
    pg.click('#auCreate'); time.sleep(0.8)
    t.check('code step', pg.is_visible('#fCode'))
    args = pg.evaluate('window.__signupArgs')
    t.eq('terms version sent = LEGAL.version', (args.get('terms') or {}).get('version'), pg.evaluate('LEGAL.version'))
    t.check('resend cooldown active', pg.is_disabled('#auResend'), pg.inner_text('#auResend'))
    pg.keyboard.type('111111'); time.sleep(0.8)
    t.check('wrong code error', 'שגוי' in pg.inner_text('#auCodeE'), pg.inner_text('#auCodeE'))
    pg.evaluate("(()=>{const d=Date.now.bind(Date);Date.now=()=>d()+61000})()"); time.sleep(1.2)
    t.check('resend enabled after 60 s', not pg.is_disabled('#auResend'), pg.inner_text('#auResend'))
    pg.click('#auResend'); time.sleep(0.4)
    t.eq('resend called', pg.evaluate('window.__resends'), 1)
    t.check('cooldown restarted', pg.is_disabled('#auResend'))
    pg.focus('#auCode'); pg.evaluate("(()=>{const i=document.getElementById('auCode');i.value='222 222';i.dispatchEvent(new Event('input',{bubbles:true}))})()"); time.sleep(1.2)
    t.check('pasted code (with a space) → welcome', pg.is_visible('#auDone'), pg.inner_text('#authTitle'))
    t.shot(pg, 's4_done')
    pg.click('#auDoneGo'); time.sleep(0.5)
    t.check('dialog closed', pg.is_hidden('#authDlg'))
    t.check('header signed in (account button, no sign-in/up)', pg.is_visible('#accBtn') and pg.is_hidden('#signInBtn') and pg.is_hidden('#signUpBtn'))
    ctx.close()

    t.section('confirmation off + terms in admin details')
    ctx, pg = lib.page(b, srv, t, mock=lib.auth_mock(confirm=False), lang='he')
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    pg.click('#signUpBtn'); time.sleep(0.4)
    pg.fill('#upUser', 'oshri'); pg.fill('#upEmail', 'o@x.com'); pg.fill('#upPass', 'Owner-Pass-123'); pg.fill('#upPass2', 'Owner-Pass-123'); time.sleep(0.6)
    pg.click('#fUp .au-cta'); time.sleep(0.4); pg.click('label.au-chk:has(#auAgree)'); pg.click('label.au-chk:has(#auAge)'); pg.click('#auCreate'); time.sleep(1)
    t.check('welcome without a code', pg.is_visible('#auDone'), pg.inner_text('#authTitle'))
    pg.click('#auDoneGo'); time.sleep(0.3)
    t.eq('terms stored on the profile', pg.evaluate("__mock.profiles.find(p=>p.username==='oshri').terms_version"), pg.evaluate('LEGAL.version'))
    pg.click('#adminBtn'); time.sleep(1)
    pg.click('#uBody tr:has-text("dana") button:has-text("פרטים")'); time.sleep(0.8)
    facts = pg.inner_text('#udFacts')
    t.check('dana (no terms data) details render', 'dana' in facts.lower() or len(facts.strip()) > 20, facts[:100])
    pg.click('#udBack'); time.sleep(0.3); pg.click('#uBody tr:has-text("oshri") button:has-text("פרטים")'); time.sleep(0.8)
    facts = pg.inner_text('#udFacts'); i = facts.find('תנאים')
    t.check('oshri details show the terms version', i >= 0 and pg.evaluate('LEGAL.version') in facts[i:i + 80], facts[i:i + 80])
    ctx.close()

    t.section('en + ar dark dialogs')
    for lang, dark, btn in [('en', False, '#signUpBtn'), ('ar', True, '#signInBtn')]:
        ctx, pg = lib.page(b, srv, t, mock=lib.auth_mock(), lang=lang, theme='dark' if dark else 'light')
        pg.goto(srv.url('#tool')); lib.wait_booted(pg); pg.click(btn); time.sleep(0.5)
        t.check(f'{lang}: dialog open, dir', pg.is_visible('#authBox') and pg.evaluate("document.documentElement.dir") == ('rtl' if lang == 'ar' else 'ltr'))
        t.shot(pg, f'dialog_{lang}')
        ctx.close()
