"""Points v2 in the browser (mock backend with the same price rules as schema.sql "Points v2"):
1. Crate: a normal user with 10 points adds 3 new files → ONE confirmation "3 songs × 1 = 3 points · balance 10 → 7" →
   charged per song after its analysis → 7; the same files again → no dialog, free (charged_songs); the account panel
   lists "Song analysis" rows.
2. Crate "USB for Pioneer": chip "3 pts" on the button, one confirmation for the folder → ZIP with 3 songs → 4;
   ledger label "Folder export ×3". The renamed-copies ZIP costs the same ('usb' × songs): a double click asks once and
   charges once (also with "don't ask again"), a failed ZIP is refunded. A batch charge whose page died (crash journal in
   localStorage + Web Lock) is refunded on the next visit, minus delivered units; a job still running (here or in
   another tab) never is.
3. Pro plan −10 %: 45 × 1 → 41 (the dialog shows the plan line and "balance 100 → 59"); short of points (1 point,
   3 rows) → "enough for the first 1" + "Buy points" + "Only the first 1" → a ZIP with only 1 song; Buy → #pricing.
4. Tool upload: a new song asks "1 point" (once) and charges after the analysis; uploading it again is free. DJ deck
   load of a song already paid is free.
5. Converter: 3 files (one broken) → chip "3 pts", one confirmation, the failed file is refunded → balance −2.
6. Mashup + Extended exports: charged once each (same render / same mix again in another format = free).
7. Admin → no dialog, no charge. Billing off → no dialog, no charge.
8. Pricing page: the price list is generated from billing.costs (one row per kind, a column per discounted plan),
   plan cards show their discount; admin settings: edit a cost per kind + a plan discount → saved → chips follow.
9. The dialog in he + ar (RTL) at 375 px in the dark theme: no horizontal scroll, inside the viewport, dark, focus
   trapped; zero CSP violations.
"""
import os, sys, io, json, time, struct, zipfile, tempfile
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import lib

FIX3 = [lib.fixture(f'p{i}.mp3') for i in range(3)]
TMP = tempfile.mkdtemp(prefix='cr-pts-')
sys.path.insert(0, lib.FIX)
import gen_club
CLUB = gen_club.make(os.path.join(TMP, 'Test Artist - Club Track.wav'))   # the Extended generator needs a real arrangement

def wav_file(name, secs=3.0, sr=44100, f=220.0):
    import math
    n = int(secs * sr); data = bytearray()
    for i in range(n):
        v = int(0.3 * 32767 * math.sin(2 * math.pi * f * i / sr)); data += struct.pack('<hh', v, v)
    hdr = b'RIFF' + struct.pack('<I', 36 + len(data)) + b'WAVEfmt ' + struct.pack('<IHHIIHH', 16, 1, 2, sr, sr * 4, 4, 16) + b'data' + struct.pack('<I', len(data))
    p = os.path.join(TMP, name); open(p, 'wb').write(hdr + data); return p

def pay(pg, kind, qty, o=None): pg.evaluate("a=>{window.__p=undefined;CR.payN(a[0],a[1],a[2]||{}).then(r=>{window.__p=r})}", [kind, qty, o])
def paid(pg, timeout=10): lib.poll(pg, "window.__p!==undefined", timeout); return pg.evaluate("window.__p")
def bal(pg): return pg.evaluate("__mock.profiles.find(p=>p.id===Backend.user.id).credits")
def chip(pg): return pg.evaluate("(document.querySelector('#creditsN')||{}).textContent")
def ledger(pg): return pg.evaluate("__mock.ledger.filter(r=>r.user_id===Backend.user.id).map(r=>[r.reason,r.ref,r.delta])")
def dlg(pg): return pg.evaluate("(()=>{const d=document.querySelector('#ptsDlg');if(!d)return null;const v=s=>{const e=d.querySelector(s);return e&&!e.hidden&&!e.closest('[hidden]')?e.textContent:null};return {h:v('h3'),calc:v('.ptscalc'),disc:v('.ptsdisc'),bal:v('.ptsbal'),short:v('.ptsshort'),go:v('.go'),part:v('.part'),skip:v('.sepskip span')}})()")
def wait_dlg(pg, timeout=15): lib.poll(pg, "!!document.querySelector('#ptsDlg')", timeout); time.sleep(0.15); return dlg(pg)
def no_dlg(pg, secs=1.5):
    t0 = time.time()
    while time.time() - t0 < secs:
        if pg.evaluate("!!document.querySelector('#ptsDlg')"): return False
        time.sleep(0.1)
    return True
def crate_done(pg, n, timeout=90):
    lib.poll(pg, f"CRATE._C.rows.length==={n}&&!CRATE._C.running&&CRATE._C.rows.every(r=>['ok','err','pause'].includes(r.st))", timeout)
def zip_names(dl):
    return sorted(zipfile.ZipFile(io.BytesIO(open(dl.value.path(), 'rb').read())).namelist())

@lib.main
def test(t, srv, b):
    # ------------------------------------------------------------------ 1. Crate analysis
    t.section('crate: 3 new songs, one confirmation')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='en', init=lib.CSP_INIT)
    pg.goto(srv.url('#crate')); lib.wait_booted(pg)
    pg.evaluate("__mock.setCredits(10,'u0')")
    lib.sign_in(pg, 'dana@example.com', 'password1')
    lib.poll(pg, "!document.querySelector('#crateView').hidden&&!!document.querySelector('#crIn')", 15)
    lib.poll(pg, "document.querySelector('#creditsN').textContent==='10'", 10)
    pg.set_input_files('#crIn', FIX3)
    d = wait_dlg(pg)
    t.eq('dialog: 3 songs × 1 = 3 points', d and d['calc'], '3 songs × 1 = 3 points')
    t.eq('dialog: balance 10 → 7', d and d['bal'], 'balance 10 → 7')
    t.check('dialog: title + confirm label', d and d['h'] == 'Analyse 3 songs' and d['go'] == 'Confirm · 3 points' and d['disc'] is None and d['part'] is None, d)
    t.check('nothing charged before confirming', bal(pg) == 10 and pg.evaluate("CRATE._C.rows.every(r=>r.st==='q')"), bal(pg))
    t.check('dialog focused on its confirm button', pg.evaluate("document.activeElement===document.querySelector('#ptsDlg .go')"))
    t.shot(pg, '01-crate-confirm')
    pg.click('#ptsDlg .go')
    crate_done(pg, 3)
    t.check('3 rows analysed', pg.evaluate("CRATE._C.rows.every(r=>r.st==='ok')"), pg.evaluate("CRATE._C.rows.map(r=>r.st)"))
    t.eq('balance 7 (server)', bal(pg), 7)
    lib.poll(pg, "document.querySelector('#creditsN').textContent==='7'", 5)
    t.eq('header chip 7', chip(pg), '7')
    t.eq('3 song charges in the ledger', [r[1].split(' ')[0] for r in ledger(pg) if r[0] == 'spend'], ['song', 'song', 'song'])
    t.section('crate: the same files again → free')
    pg.evaluate("CRATE._C.rows=[];CRATE.lang()")
    pg.set_input_files('#crIn', FIX3)
    t.check('no dialog for songs already paid', no_dlg(pg, 2.0))
    crate_done(pg, 3)
    t.check('analysed again, still 7', pg.evaluate("CRATE._C.rows.every(r=>r.st==='ok')") and bal(pg) == 7, bal(pg))

    # ------------------------------------------------------------------ 2. USB export
    t.section('crate: USB for Pioneer = one charge for the folder')
    t.eq('USB button chip: 3 pts', pg.evaluate("document.querySelector('#crUsbPts').hidden?null:document.querySelector('#crUsbPts').textContent"), '3 pts')
    pg.click('#crUsb')
    d = wait_dlg(pg)
    t.check('USB dialog: 3 songs × 1 = 3 points, 7 → 4', d and d['calc'] == '3 songs × 1 = 3 points' and d['bal'] == 'balance 7 → 4' and 'USB' in d['h'], d)
    with pg.expect_download(timeout=60000) as dl: pg.click('#ptsDlg .go')
    names = zip_names(dl)
    t.check('ZIP: 3 songs + playlist', len([n for n in names if n.endswith('.mp3')]) == 3 and 'Chord Room.m3u8' in names, names)
    t.eq('balance 4', bal(pg), 4)
    t.check('ledger: usb ×3', any(r[0] == 'spend' and r[1].startswith('usb ×3') and r[2] == -3 for r in ledger(pg)), ledger(pg))
    pg.evaluate("document.querySelector('#accBtn').click()"); time.sleep(0.4)
    pg.evaluate("(()=>{const d=document.querySelector('#ptsBox details');d.open=true})()")
    lib.poll(pg, "document.querySelectorAll('#ptsLog li').length>=4", 10)
    items = pg.eval_on_selector_all('#ptsLog li .lr', 'e=>e.map(x=>x.textContent)')
    t.check('account panel: "Folder export ×3 · USB for Pioneer" and "Song analysis" labels', any(x.startswith('Used · Folder export ×3 · USB for Pioneer') for x in items) and any('Song analysis' in x for x in items), items[:5])
    t.shot(pg, '02-ledger')
    pg.keyboard.press('Escape'); time.sleep(0.3)
    t.check('USB settled: no crash journal left', pg.evaluate("localStorage.getItem('chordroom.payjobs.v1')") is None)

    t.section('crate: renamed copies (ZIP) = the same folder price, once per click')
    pg.evaluate("__mock.setCredits(20)"); pg.evaluate("CR.refreshPoints()"); time.sleep(0.4)
    t.eq('ZIP button chip: 3 pts', pg.evaluate("document.querySelector('#crZipPts').hidden?null:document.querySelector('#crZipPts').textContent"), '3 pts')
    pg.evaluate("document.querySelector('#crZip').click();document.querySelector('#crZip').click()")
    d = wait_dlg(pg)
    t.check('double click → ONE dialog: "Renamed copies · 3 songs", 3 × 1 = 3, 20 → 17',
            pg.evaluate("document.querySelectorAll('#ptsDlg').length") == 1 and d and d['h'] == 'Renamed copies · 3 songs' and d['calc'] == '3 songs × 1 = 3 points' and d['bal'] == 'balance 20 → 17', d)
    t.check('both folder buttons are busy while asking', pg.evaluate("document.querySelector('#crZip').disabled&&document.querySelector('#crUsb').disabled"))
    with pg.expect_download(timeout=60000) as dl: pg.click('#ptsDlg .go')
    names = zip_names(dl)
    t.check('renamed ZIP: 3 songs + playlist', len([n for n in names if n.endswith('.mp3')]) == 3 and 'Chord Room.m3u8' in names, names)
    t.eq('balance 17', bal(pg), 17)
    t.check('ledger: "usb ×3 Renamed copies (ZIP)"', any(r[0] == 'spend' and r[1] == 'usb ×3 Renamed copies (ZIP)' and r[2] == -3 for r in ledger(pg)), ledger(pg)[-3:])
    lib.poll(pg, "!CRATE._C.zipBusy", 10)
    t.check('ZIP settled: no crash journal left', pg.evaluate("localStorage.getItem('chordroom.payjobs.v1')") is None)
    pg.evaluate("localStorage.setItem('chordroom.payok.v1:'+Backend.user.id,JSON.stringify({usb:10}))")   # per account (sec)
    n0 = len(ledger(pg))
    with pg.expect_download(timeout=60000) as dl: pg.evaluate("document.querySelector('#crZip').click();document.querySelector('#crZip').click()")
    lib.poll(pg, "!CRATE._C.zipBusy", 10); time.sleep(0.5)
    t.check('"don\'t ask again" + double click → ONE charge (17 → 14)', bal(pg) == 14 and sum(1 for r in ledger(pg)[n0:] if r[0] == 'spend') == 1, (bal(pg), ledger(pg)[n0:]))
    t.allow_errors.append('test-induced ZIP failure')
    pg.evaluate("(()=>{const z=CR.zip;CR.zip=()=>{CR.zip=z;throw new Error('test-induced ZIP failure')}})()")
    n0 = len(ledger(pg))
    pg.click('#crZip')
    lib.poll(pg, f"__mock.ledger.length>{n0 + 1}&&!CRATE._C.zipBusy", 10)
    new = ledger(pg)[n0:]
    t.check('ZIP fails → charged 3 and the 3 points come back', bal(pg) == 14 and [r[0] for r in new] == ['spend', 'refund'] and new[1][2] == 3, new)
    t.check('… with an error message', "Couldn't read" in pg.inner_text('#crMsg'), pg.inner_text('#crMsg'))
    pg.evaluate("localStorage.removeItem('chordroom.payok.v1:'+Backend.user.id)")

    t.section('a batch charge whose page died is refunded on the next visit')
    J = "JSON.parse(localStorage.getItem('chordroom.payjobs.v1')||'[]')"
    pg.evaluate("__mock.setCredits(30)"); pg.evaluate("CR.refreshPoints()"); time.sleep(0.3)
    pg.evaluate("Backend.spendN('usb',3,'crash').then(r=>localStorage.setItem('chordroom.payjobs.v1',JSON.stringify([{id:r.id,uid:Backend.user.id,kind:'usb',qty:3,done:1,t:Date.now()},{id:999,uid:'someone-else',kind:'usb',qty:5,done:0,t:Date.now()}])))")
    lib.poll(pg, f"{J}.length===2", 5); t.eq('charged 3 → 27', bal(pg), 27)
    pg.evaluate("CR._payJobsCheck()")
    lib.poll(pg, "__mock.profiles.find(p=>p.id===Backend.user.id).credits===29", 5)
    t.check('dead job: the 2 undelivered units are refunded, a toast says so, other accounts\' jobs stay',
            bal(pg) == 29 and pg.evaluate(f"{J}.map(j=>j.id).join()") == '999' and 'returned' in pg.inner_text('#toast'), (bal(pg), pg.evaluate(J), pg.inner_text('#toast')))
    pg.evaluate("CR._payJobsCheck()"); time.sleep(0.6)
    t.eq('checking again refunds nothing more', bal(pg), 29)
    # a job still running in another tab (its Web Lock is held) is never refunded
    oid = pg.evaluate("Backend.spendN('usb',4,'other tab').then(r=>{localStorage.setItem('chordroom.payjobs.v1',JSON.stringify([{id:r.id,uid:Backend.user.id,kind:'usb',qty:4,done:0,t:Date.now()}]));"
                      "navigator.locks.request('crpay:'+r.id,()=>new Promise(ok=>{window.__rel=ok}));return r.id})")
    time.sleep(0.3); pg.evaluate("CR._payJobsCheck()"); time.sleep(0.8)
    t.check('running in another tab (lock held) → not refunded, kept in the journal', bal(pg) == 25 and pg.evaluate(f"{J}.length") == 1, (bal(pg), pg.evaluate(J)))
    pg.evaluate("window.__rel()"); time.sleep(0.2); pg.evaluate("CR._payJobsCheck()")
    lib.poll(pg, "__mock.profiles.find(p=>p.id===Backend.user.id).credits===29", 5)
    t.check('that tab died (lock gone) → refunded', bal(pg) == 29 and pg.evaluate(f"{J}.length") == 0, bal(pg))
    # a job running in THIS tab: journaled while it runs, never refunded by the check, gone after settleN
    pg.evaluate("localStorage.setItem('chordroom.payok.v1:'+Backend.user.id,JSON.stringify({usb:10}))")   # per account (sec)
    pay(pg, 'usb', 2); r = paid(pg)
    t.check('payN journals the running job', r and r.get('id') and pg.evaluate(f"{J}.map(j=>j.id+':'+j.qty).join()") == f"{r.get('id')}:2", (r, pg.evaluate(J)))
    pg.evaluate("CR._payJobsCheck()"); time.sleep(0.8)
    t.eq('running here → not refunded', bal(pg), 27)
    pg.evaluate("CR.settleN(window.__p,0)"); time.sleep(0.3)
    t.check('settleN(pay, 0) → journal empty, nothing refunded', pg.evaluate(f"{J}.length") == 0 and bal(pg) == 27, (bal(pg), pg.evaluate(J)))
    pg.evaluate("localStorage.removeItem('chordroom.payok.v1:'+Backend.user.id)")

    # ------------------------------------------------------------------ 3. plan discount, short of points
    t.section('Pro plan −10 % and rounding')
    pg.evaluate("__mock.setCredits(100);__mock.setPlan('pro',10)"); pg.evaluate("CR.refreshPoints()"); time.sleep(0.5)
    t.check('client price: usb ×45 on Pro = 41, ×3 = 3, sep = 5', pg.evaluate("[CR.price('usb',45).total,CR.price('usb',3).total,CR.price('sep',1).total,CR.price('usb',45).discount]") == [41, 3, 5, 10],
            pg.evaluate("[CR.price('usb',45),CR.price('usb',3)]"))
    pay(pg, 'usb', 45, {'ref': 'test 45'})
    d = wait_dlg(pg)
    t.check('dialog: 45 songs × 1 = 45 points · your plan Pro −10% → 41 · balance 100 → 59',
            d and d['calc'] == '45 songs × 1 = 45 points' and d['disc'] == 'your plan Pro −10% → 41' and d['bal'] == 'balance 100 → 59', d)
    t.shot(pg, '03-pro-discount')
    pg.click('#ptsDlg .go'); r = paid(pg)
    t.check('charged 41 → 59', r and r['charged'] == 41 and bal(pg) == 59, (r, bal(pg)))
    t.section('short of points: only the first K / buy points')
    pg.evaluate("__mock.setCredits(1);__mock.setPlan('free',0)"); pg.evaluate("CR.refreshPoints()"); time.sleep(0.4)
    pg.click('#crUsb')
    d = wait_dlg(pg)
    t.check('short: "you have 1, enough for the first 1" + Buy points + Only the first 1', d and d['short'] == 'Not enough points: you have 1, enough for the first 1.' and d['go'] == 'Buy points' and d['part'] == 'Only the first 1' and d['bal'] is None and d['skip'] is None, d)
    t.shot(pg, '04-short')
    with pg.expect_download(timeout=60000) as dl: pg.click('#ptsDlg .part')
    names = zip_names(dl)
    t.check('ZIP with only the first song', len([n for n in names if n.endswith('.mp3')]) == 1, names)
    t.eq('balance 0', bal(pg), 0)
    lib.poll(pg, "/left out/.test(document.querySelector('#crMsg').textContent)", 5)
    t.check('message: 2 songs left out', '2 songs were left out' in pg.inner_text('#crMsg'), pg.inner_text('#crMsg'))
    pg.click('#crUsb'); d = wait_dlg(pg)
    t.check('0 points: "this costs 3 and you have 0", no partial', d and d['short'] == 'Not enough points: this costs 3 and you have 0.' and d['part'] is None, d)
    pg.click('#ptsDlg .go')
    lib.poll(pg, "!document.querySelector('#pricingView').hidden", 5)
    t.check('"Buy points" opens the pricing page, nothing charged', bal(pg) == 0 and not pg.evaluate("!!document.querySelector('#ptsDlg')"))
    pg.evaluate("__mock.setCredits(20)"); pg.evaluate("CR.refreshPoints()"); time.sleep(0.3)

    t.section('"don\'t ask again" up to N points')
    pay(pg, 'mashup', 1); d = wait_dlg(pg)
    t.eq('skip label', d and d['skip'], "Don't ask again for Mashup export up to 3 points")
    pg.check('#ptsDlg .sepskip input'); pg.click('#ptsDlg .go'); time.sleep(0.3)
    pay(pg, 'mashup', 1)
    t.check('second time: no dialog, charged', no_dlg(pg, 1.0) and (paid(pg) or {}).get('charged') == 3 and bal(pg) == 14, (pg.evaluate("window.__p"), bal(pg)))
    pay(pg, 'usb', 4); d = wait_dlg(pg)
    t.check('another kind still asks', d is not None, d)
    pg.click('#ptsDlg .no'); t.check('cancel → null, nothing charged', paid(pg) is None and bal(pg) == 14)
    pg.evaluate("localStorage.removeItem('chordroom.payok.v1:'+Backend.user.id)")
    t.eq('zero CSP violations', lib.csp_violations(pg), [])
    ctx.close()

    # ------------------------------------------------------------------ 4. tool + DJ
    t.section('tool upload: once per song; DJ: a paid song is free')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='en')
    pg.goto(srv.url('#tool')); lib.wait_booted(pg); lib.wait_tool_song(pg)
    lib.sign_up(pg, 'newbie', 'n@x.com'); time.sleep(0.5)
    pg.evaluate("__mock.setCredits(5)"); pg.evaluate("CR.refreshPoints()"); time.sleep(0.3)
    pg.set_input_files('#file', FIX3[2])
    d = wait_dlg(pg)
    t.check('tool: "Song analysis · 1 point", balance 5 → 4', d and d['h'] == 'Song analysis' and d['calc'] == '1 point' and d['bal'] == 'balance 5 → 4', d)
    pg.click('#ptsDlg .go'); lib.wait_tool_song(pg, 'p2')
    lib.poll(pg, "__mock.profiles.find(p=>p.id===Backend.user.id).credits===4", 10)
    t.eq('charged 1 after the analysis', bal(pg), 4)
    pg.set_input_files('#file', FIX3[2])
    t.check('the same file again → no dialog', no_dlg(pg, 2.0))
    lib.wait_tool_song(pg, 'p2'); t.eq('still 4', bal(pg), 4)
    pg.evaluate("location.hash='#dj'"); lib.poll(pg, "!document.querySelector('#djView').hidden&&!!document.querySelector('#djFile')", 15)
    pg.set_input_files('#djFile', FIX3[2])
    t.check('DJ: a song already paid loads with no dialog', no_dlg(pg, 2.0))
    lib.poll(pg, "DJ._D.decks.some(d=>d.track&&/p2/.test(d.track.name))&&!DJ._D.decks.some(d=>d.loading)", 40)
    t.eq('DJ: still 4', bal(pg), 4)
    pg.set_input_files('#djFile', FIX3[1])
    d = wait_dlg(pg)
    t.check('DJ: a new file asks for 1 point', d and d['calc'] == '1 point' and d['go'] == 'Confirm · 1 point', d)
    pg.click('#ptsDlg .go')
    lib.poll(pg, "__mock.profiles.find(p=>p.id===Backend.user.id).credits===3", 40)
    t.eq('DJ: charged after loading → 3', bal(pg), 3)
    ctx.close()

    # ------------------------------------------------------------------ 5. Converter
    t.section('converter: 3 files, one broken → refunded')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='en', init=lib.CSP_INIT)
    pg.goto(srv.url('#convert')); lib.wait_booted(pg)
    pg.evaluate("__mock.setCredits(10,'u0')"); lib.sign_in(pg, 'dana@example.com', 'password1')
    lib.poll(pg, "!document.querySelector('#convertView').hidden&&!!document.querySelector('#cvFile')", 15)
    pg.evaluate("o=>{Object.assign(CONVERT._C.o,o);CONVERT.lang()}", {'fmt': 'wav', 'q': 16, 'norm': False, 'trim': False, 'bk': False})
    bad = os.path.join(TMP, 'broken.mp3'); open(bad, 'wb').write(os.urandom(4096))
    pg.set_input_files('#cvFile', [wav_file('a.wav'), wav_file('b.wav', f=330), bad])
    lib.poll(pg, "CONVERT._C.rows.length===3&&!!document.querySelector('#cvPts')", 10)
    t.eq('Convert button chip: 3 pts', pg.inner_text('#cvPts'), '3 pts')
    pg.click('#cvGo')
    d = wait_dlg(pg)
    t.check('dialog: 3 files × 1 = 3 points, 10 → 7', d and d['calc'] == '3 files × 1 = 3 points' and d['bal'] == 'balance 10 → 7', d)
    pg.click('#ptsDlg .go')
    lib.poll(pg, "!CONVERT._C.running&&CONVERT._C.rows.every(r=>['done','error','cancelled'].includes(r.status))", 90)
    st = pg.evaluate("CONVERT._C.rows.map(r=>r.status)")
    t.check('2 done, 1 error', sorted(st) == ['done', 'done', 'error'], st)
    lib.poll(pg, "__mock.profiles.find(p=>p.id===Backend.user.id).credits===8", 10)
    t.eq('charged 3, refunded 1 → 8', bal(pg), 8)
    t.check('ledger: convert ×3 then a refund of 1', any(r[1].startswith('convert ×3') and r[2] == -3 for r in ledger(pg)) and any(r[0] == 'refund' and r[2] == 1 for r in ledger(pg)), ledger(pg))
    t.eq('zero CSP violations (converter)', lib.csp_violations(pg), [])

    # ------------------------------------------------------------------ 6. Mashup + Extended
    t.section('mashup export: charged once for the same mix')
    pg.evaluate("__mock.setCredits(20)"); pg.evaluate("CR.refreshPoints()")
    pg.evaluate("location.hash='#mashup'"); lib.poll(pg, "!document.querySelector('#mashupView').hidden&&!!document.querySelector('#mxIn')", 15)
    pg.evaluate("MASHUP._M.pickFor=0"); pg.set_input_files('#mxIn', FIX3[0])
    lib.poll(pg, "!!(MASHUP._M.slots[0].song&&MASHUP._M.slots[0].song.an)&&!MASHUP._M.slots[0].loading", 60)
    pg.evaluate("MASHUP._M.pickFor=1"); pg.set_input_files('#mxIn', FIX3[1])
    lib.poll(pg, "!!(MASHUP._M.slots[1].song&&MASHUP._M.slots[1].song.an)&&!MASHUP._M.slots[1].loading&&!document.querySelector('#mxExp').disabled", 60)
    t.check('no song charge for Mashup loads (export pays)', bal(pg) == 20 and not pg.evaluate("!!document.querySelector('#ptsDlg')"), bal(pg))
    t.eq('export chip: 3 pts', pg.evaluate("document.querySelector('#mxExpPts').hidden?null:document.querySelector('#mxExpPts').textContent"), '3 pts')
    pg.click('#mxExp'); d = wait_dlg(pg)
    t.check('mashup dialog: 3 points, 20 → 17', d and d['calc'] == '3 points' and d['bal'] == 'balance 20 → 17' and d['h'] == 'Mashup export', d)
    with pg.expect_download(timeout=120000) as dl: pg.click('#ptsDlg .go')
    t.check('mashup file downloaded', dl.value.suggested_filename.endswith('.wav'), dl.value.suggested_filename)
    t.eq('mashup: 17', bal(pg), 17)
    lib.poll(pg, "document.querySelector('#mxExpPts').hidden", 5)
    pg.evaluate("document.querySelector('#mxFmt [data-fm=mp3]')&&!document.querySelector('#mxFmt [data-fm=mp3]').disabled&&document.querySelector('#mxFmt [data-fm=mp3]').click()")
    with pg.expect_download(timeout=120000) as dl: pg.click('#mxExp')
    t.check('same mix in another format: no dialog, no charge', not pg.evaluate("!!document.querySelector('#ptsDlg')") and bal(pg) == 17, (dl.value.suggested_filename, bal(pg)))
    pg.evaluate("MASHUP._M.nudge=(MASHUP._M.nudge||0)+1;MASHUP.lang()")
    pg.click('#mxExp'); d = wait_dlg(pg)
    t.check('a changed mix asks again', d is not None and d['calc'] == '3 points', d)
    pg.click('#ptsDlg .no'); time.sleep(0.3); t.eq('cancelled → still 17', bal(pg), 17)

    t.section('extended export: charged once for the same render')
    pg.evaluate("location.hash='#extended'"); lib.poll(pg, "!document.querySelector('#extendedView').hidden&&!!document.querySelector('#exIn')", 15)
    pg.set_input_files('#exIn', CLUB)
    lib.poll(pg, "EXTENDED._X.stage==='ready'||!!EXTENDED._X.msg", 200)
    t.check('extended: analysed (no song charge)', pg.evaluate("EXTENDED._X.stage==='ready'") and bal(pg) == 17, pg.evaluate("EXTENDED._X.msg"))
    pg.click('#exSet [data-a="gen"]'); lib.poll(pg, "EXTENDED._X.stage==='done'", 120)
    lib.poll(pg, "!!document.querySelector('#exExpPts')", 10)
    t.eq('extended export chip: 3 pts', pg.evaluate("document.querySelector('#exExpPts').hidden?null:document.querySelector('#exExpPts').textContent"), '3 pts')
    pg.click('#exExp [data-fm="wav16"]'); time.sleep(0.2)
    pg.evaluate("(()=>{const b=document.querySelector('#exExp [data-a=\"exp\"]');b.click();b.click()})()"); d = wait_dlg(pg)
    t.check('extended: a double click opens ONE dialog', pg.evaluate("document.querySelectorAll('#ptsDlg').length") == 1)
    t.check('extended dialog: 3 points, 17 → 14', d and d['calc'] == '3 points' and d['bal'] == 'balance 17 → 14' and d['h'] == 'Extended export', d)
    with pg.expect_download(timeout=150000) as dl: pg.click('#ptsDlg .go')
    t.check('extended file downloaded', 'Extended Mix' in dl.value.suggested_filename, dl.value.suggested_filename)
    t.eq('extended: 14', bal(pg), 14)
    pg.click('#exExp [data-fm="wav24"]'); time.sleep(0.2)
    with pg.expect_download(timeout=150000) as dl: pg.click('#exExp [data-a="exp"]')
    t.check('same render again (24-bit): no dialog, no charge', not pg.evaluate("!!document.querySelector('#ptsDlg')") and bal(pg) == 14, bal(pg))
    t.check('chip hidden once the render is paid', pg.evaluate("document.querySelector('#exExpPts').hidden"))
    t.check('ledger: mashup ×1 + extended ×1', sum(1 for r in ledger(pg) if r[1].startswith('mashup ×1')) == 1 and sum(1 for r in ledger(pg) if r[1].startswith('extended ×1')) == 1, ledger(pg))
    t.eq('zero CSP violations (mashup/extended)', lib.csp_violations(pg), [])
    ctx.close()

    # ------------------------------------------------------------------ 7. admin, billing off
    t.section('admin: free, never asked; billing off: free')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='en')
    pg.goto(srv.url('#crate')); lib.wait_booted(pg)
    lib.sign_up(pg, 'oshri', 'o@x.com')
    lib.poll(pg, "!document.querySelector('#crateView').hidden&&!!document.querySelector('#crIn')", 15)
    b0 = bal(pg)
    pg.set_input_files('#crIn', FIX3[:2])
    t.check('admin: no dialog on new songs', no_dlg(pg, 2.0))
    crate_done(pg, 2)
    t.check('admin: USB chip hidden (free)', pg.evaluate("document.querySelector('#crUsbPts').hidden"))
    with pg.expect_download(timeout=60000) as dl: pg.click('#crUsb')
    t.check('admin: USB export without a dialog, balance unchanged, no ledger rows', not pg.evaluate("!!document.querySelector('#ptsDlg')") and bal(pg) == b0 and not ledger(pg), (bal(pg), ledger(pg)))
    t.check('admin: CR.price says free', pg.evaluate("CR.price('usb',10).free&&CR.price('usb',10).total===0&&CR.priceChip('usb',10)===''"))

    t.section('admin settings: a cost per kind + plan discounts')
    pg.evaluate("document.querySelector('#adminBtn').click()"); time.sleep(0.6)
    pg.click('#admTabs button[data-v="settings"]'); time.sleep(0.5)
    kinds = pg.eval_on_selector_all('#bCosts input[data-kind]', 'e=>e.map(x=>x.dataset.kind+"="+x.value)')
    t.eq('one field per kind with the defaults', kinds, ['song=1', 'sep=5', 'stems=2', 'usb=1', 'mashup=3', 'extended=3', 'convert=1'])
    labels = pg.eval_on_selector_all('#bCosts label', 'e=>e.map(x=>x.textContent)')
    t.check('labelled (en)', labels[3] == 'Crate folder export: USB for Pioneer / renamed copies (per song)' and labels[0].startswith('Analysing an uploaded song'), labels)
    t.eq('plan discount fields 0/10/25', pg.eval_on_selector_all('#bPlans [data-f=discount]', 'e=>e.map(x=>x.value)'), ['0', '10', '25'])
    pg.fill('#bCost_usb', '2'); pg.fill('#bCost_convert', '0')
    pg.fill('#bPlans .bplan:nth-child(2) [data-f=discount]', '20')
    pg.click('#bSave'); lib.poll(pg, "(__mock.cfg.billing||{}).costs&&__mock.cfg.billing.costs.usb===2", 5)
    cfgb = pg.evaluate("__mock.cfg.billing")
    t.check('saved: usb 2, convert 0, pro discount 20, other kinds kept', cfgb['costs'] == {'song': 1, 'sep': 5, 'stems': 2, 'usb': 2, 'mashup': 3, 'extended': 3, 'convert': 0} and [p.get('discount') for p in cfgb['plans']] == [0, 20, 25], cfgb)
    t.shot(pg, '07-admin-costs')
    pg.keyboard.press('Escape'); time.sleep(0.3)

    t.section('pricing page: generated price list')
    pg.evaluate("location.hash='#pricing'"); lib.poll(pg, "!!document.querySelector('#pricingView .pg-tbl')", 10)
    head = pg.eval_on_selector_all('#pricingView .pg-tbl thead th', 'e=>e.map(x=>x.textContent)')
    t.eq('columns: action, cost, Pro −20%, Studio −25%', head, ['Action', 'Cost', 'Pro · −20%', 'Studio · −25%'])
    trs = pg.eval_on_selector_all('#pricingView .pg-tbl tbody tr', 'e=>e.map(x=>x.innerText.replace(/\\s+/g," ").trim())')
    find = lambda k: next((r for r in trs if r.startswith(k)), '')
    t.check('row: Crate folder (USB / renamed copies) · per song · 2 points · Pro 1.6 · Studio 1.5 (bare numbers under the plan columns)', find('Crate folder') == 'Crate folder: USB for Pioneer or renamed copies (cue points, tags) per song 2 points 1.6 1.5', find('Crate folder'))
    t.check('row: song analysis once per song', find('Analysing a song') .startswith('Analysing a song you upload once per song 1 point'), find('Analysing a song'))
    t.check('row: conversion priced 0 → Free', find('File conversion') == 'File conversion Free', find('File conversion'))
    t.check('rows: separation, stems, mashup, extended + free rows + gift', all(find(k) for k in ['AI stem separation', 'Stems download', 'Mashup export', 'Extended mix export', 'Reopening your songs', 'MIDI export', 'Library exports', 'Signup gift']), trs)
    t.check('note about rounding the total', 'rounded up' in pg.inner_text('#pricingView .pg-tnote'))
    cards = pg.eval_on_selector_all('#pricingView .pg-plan', 'e=>e.map(x=>(x.querySelector(".pg-disc")||{}).textContent||"")')
    t.eq('plan cards: discount lines', cards, ['', '', '−20% on every action', '−25% on every action'])
    t.check('"−20%" isolated LTR (stays in one piece in RTL)', pg.evaluate("[...document.querySelectorAll('#pricingView .pg-disc span[dir=ltr], #pricingView .pg-thd span[dir=ltr]')].map(x=>x.textContent).join(',')") == '−20%,−25%,−20%,−25%')
    t.shot(pg, '08-pricing', full_page=True)
    pg.select_option('#lang', 'he'); time.sleep(0.6)
    head = pg.eval_on_selector_all('#pricingView .pg-tbl thead th', 'e=>e.map(x=>x.textContent)')
    t.check('pricing in Hebrew: plan columns + Hebrew rows', head[2] == 'מקצועי · −20%' and 'USB לפיוניר' in pg.inner_text('#pricingView .pg-tbl'), head)
    for l in ['ar', 'ru', 'es']:
        pg.select_option('#lang', l); time.sleep(0.4)
        tx = pg.inner_text('#pricingView .pg-tbl')
        t.check(f'pricing table in {l} has no missing strings', 'rk_' not in tx and 'per_' not in tx and 'undefined' not in tx, tx[:120])
    pg.select_option('#lang', 'en'); time.sleep(0.3)

    t.section('settings reflected in chips (normal user)')
    lib.sign_out(pg); pg.evaluate("__mock.setCredits(30,'u0')"); lib.sign_in(pg, 'dana@example.com', 'password1')
    lib.poll(pg, "document.querySelector('#creditsN').textContent==='30'", 10)
    t.check('chips follow the new costs: usb ×3 = 6 pts, convert = free', pg.evaluate("[CR.priceChip('usb',3),CR.priceChip('convert',8),CR.priceChip('song',1)]") == ['6 pts', '', '1 pt'], pg.evaluate("[CR.priceChip('usb',3),CR.priceChip('convert',8)]"))
    pg.evaluate("__mock.cfg.billing={...__mock.cfg.billing,on:false}")
    pg.evaluate("Backend.getConfig().then(c=>{CR.ACC.config=c})"); time.sleep(0.2)
    pg.evaluate("location.hash='#crate'"); lib.poll(pg, "!document.querySelector('#crateView').hidden", 10)
    pg.evaluate("CR.refreshPoints()"); time.sleep(0.3)
    pg.evaluate("CRATE._C.rows=[];CRATE.lang()")
    pg.set_input_files('#crIn', [FIX3[0]])
    t.check('billing off: no dialog', no_dlg(pg, 2.0))
    crate_done(pg, 1)
    t.check('billing off: nothing charged, price free', bal(pg) == 30 and pg.evaluate("CR.price('usb',5).free"), bal(pg))
    ctx.close()

    # ------------------------------------------------------------------ 9. RTL + dark + 375 px
    for lang, word in [('he', 'אישור'), ('ar', 'تأكيد')]:
        t.section(f'dialog: {lang} RTL, dark, 375 px')
        ctx, pg = lib.page(b, srv, t, mock=True, lang=lang, theme='dark', w=375, h=780, mobile=True, init=lib.CSP_INIT)
        pg.goto(srv.url('#crate')); lib.wait_booted(pg)
        pg.evaluate("__mock.setCredits(100,'u0');__mock.setPlan('pro',10,'u0')")
        lib.sign_in(pg, 'dana@example.com', 'password1'); time.sleep(0.5)
        pay(pg, 'usb', 45); d = wait_dlg(pg)
        t.check(f'{lang}: page is RTL', pg.evaluate("document.documentElement.dir") == 'rtl')
        t.check(f'{lang}: confirm label translated, discount line shown', d and word in (d['go'] or '') and d['disc'] and '41' in d['disc'] and '\u2066−10%\u2069' in d['disc'], d)
        t.eq(f'{lang}: no horizontal scroll at 375 px', lib.scroll_width(pg), 375)
        r = pg.evaluate("(()=>{const r=document.querySelector('#ptsDlg .dlg').getBoundingClientRect();return {l:r.left,r:r.right,t:r.top,b:r.bottom}})()")
        t.check(f'{lang}: dialog inside the viewport', r['l'] >= 0 and r['r'] <= 375 and r['t'] >= 0 and r['b'] <= 780, r)
        t.check(f'{lang}: dark dialog', lib.page_luma(pg, '#ptsDlg .dlg') < 80, lib.page_luma(pg, '#ptsDlg .dlg'))
        pg.keyboard.press('Tab'); pg.keyboard.press('Tab'); pg.keyboard.press('Tab'); pg.keyboard.press('Tab')
        t.check(f'{lang}: focus stays in the dialog', pg.evaluate("!!document.activeElement.closest('#ptsDlg')"))
        t.shot(pg, f'09-{lang}-dark-375')
        pg.keyboard.press('Escape')
        t.check(f'{lang}: Esc closes, nothing charged', paid(pg) is None and bal(pg) == 100)
        t.eq(f'{lang}: zero CSP violations', lib.csp_violations(pg), [])
        ctx.close()
