"""Accounts v4 in the browser (assets/acct.js + the mock backend's v4 part), under the real CSP:
  * account panel: 2FA section, "sign out of all devices", danger zone — 5 languages, RTL (he/ar), dark, 375 px
  * 2FA: enrol (QR from a data: image, setup key, wrong code, right code) → sign in again → the code step (wrong / right),
    "sign out" from the code step; the admin panel banner until the management account has 2FA
  * delete account: confirmation, wrong password, password re-auth, e-mail code instead of the password (he: מחק),
    2FA code required, owner refused, live subscription refused with the portal link; afterwards: signed out, the
    account gone, this browser's per-user keys + remembered song removed (another account's keys kept), notice dialog
  * admin "Delete user" (full admin; never the owner)
  * Turnstile: no site key → no script, no widget; site key → Cloudflare's api.js (stubbed) loads, the widget renders in
    the auth dialog, sign-in / sign-up / reset carry a token; a failed check → message
  * idle sign-out with a fake clock: warning 60 s before the limit (users 7 days / admin-panel accounts 60 min / admin
    settings), "stay" resets, activity in another tab resets, the limit signs out + notice
  * offensive words: shared cases (fixtures/textguard_cases.py) = the SQL answers; profile form refused instantly;
    sign-up username refused; age checkbox required + "N or older" from billing.min_age + sent with the sign-up
  * admin Settings → Security (fields, owner-only 2FA switch) + blocked words list; client sign-in brake after 5 wrong passwords
"""
import os, sys, json, time
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'fixtures'))
import lib
from textguard_cases import OFFENSIVE, CLEAN

TS_STUB = r"""(()=>{let n=0;const W={};window.__tsRenders=0;
window.turnstile={render(el,o){n++;const id='w'+n;window.__tsRenders++;window.__tsOpts=Object.assign({},o,{callback:undefined});const d=document.createElement('div');d.className='cf-stub';d.textContent='turnstile';el.appendChild(d);W[id]=o;
  setTimeout(()=>{if(window.__tsFail)o['error-callback']&&o['error-callback']('x');else o.callback('tok-'+id+'-'+Date.now())},60);return id},
 reset(id){const o=W[id];if(o)setTimeout(()=>{if(window.__tsFail)o['error-callback']&&o['error-callback']('x');else o.callback('tok-'+id+'-'+Date.now())},60)},remove(id){delete W[id]},getResponse(){return ''}};})();"""

def ts_route(ctx):
    ctx.route('https://challenges.cloudflare.com/**', lambda r: r.fulfill(status=200, content_type='text/javascript', body=TS_STUB, headers={'access-control-allow-origin': '*'}))

def mock_with(cfg=None, extra=''):
    pre = ''
    if cfg:
        extra = "(()=>{const B=window.__MOCK_BACKEND;const g=B.getConfig;B.getConfig=async()=>{const c=await g();return {...c,billing:{...(c.billing||{}),...%s}}}})();\n" % json.dumps(cfg) + extra
    return lib.mock_js(extra, pre=pre)

def open_acc(pg):
    pg.click('#accBtn'); lib.poll(pg, "!document.querySelector('#acc').hidden&&!!document.querySelector('#acDelBtn')", 5); time.sleep(0.4)

def sign_in_ui(pg, email, pw):
    pg.click('#signInBtn'); time.sleep(0.3); pg.fill('#inEmail', email); pg.fill('#inPass', pw); pg.click('#fIn .au-cta'); time.sleep(0.8)

@lib.main
def test(t, srv, b):
    t.section('account panel sections, 2FA enrolment (he)')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='he', init=lib.CSP_INIT)
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    lib.sign_up(pg, 'oshri', 'o@x.com', 'Strong-Pass9')
    open_acc(pg)
    t.eq('2FA section heading (he)', pg.inner_text('#acMfaH'), 'אימות דו־שלבי (2FA)')
    t.check('2FA off status', 'כבוי' in pg.inner_text('#acMfaSt'), pg.inner_text('#acMfaSt'))
    t.eq('sign out of all devices (he)', pg.inner_text('#acOutAll'), 'יציאה מכל המכשירים')
    t.eq('danger zone button (he)', pg.inner_text('#acDelBtn'), 'מחיקת החשבון')
    t.eq('page is RTL', pg.evaluate('document.documentElement.dir'), 'rtl')
    pg.click('#acMfaOn'); lib.poll(pg, "document.querySelector('#acEnr img')", 5)
    t.check('QR is a data:image/svg+xml image', pg.evaluate("document.querySelector('#acQr img').src.startsWith('data:image/svg+xml')"))
    t.eq('setup key shown', pg.input_value('#acKey'), 'JBSWY3DPEHPK3PXP')
    t.eq('focus moved into the dialog', pg.evaluate("document.querySelector('#acEnr').contains(document.activeElement)"), True)
    t.shot(pg, 'enrol_he')
    pg.fill('#acEnrCode', '000000'); time.sleep(0.6)
    t.check('wrong code → message', 'הקוד לא התאים' in pg.inner_text('#acEnrMsg'), pg.inner_text('#acEnrMsg'))
    pg.fill('#acEnrCode', '123456'); time.sleep(0.8)
    t.check('right code → dialog closed', pg.query_selector('#acEnr') is None)
    lib.poll(pg, "document.querySelector('#acMfaSt').textContent.includes('פעיל')", 5)
    t.check('status: on + one authenticator listed', pg.evaluate("document.querySelectorAll('#acMfaList li').length") == 1)
    pg.click('#accClose'); time.sleep(0.3)

    t.section('admin banner: shown only without 2FA')
    pg.click('#adminBtn'); time.sleep(0.8)
    t.check('2FA on → no banner', not pg.is_visible('#acMfaBan'))
    pg.click('#adminClose'); time.sleep(0.2)

    t.section('sign in again → the 2FA code step')
    lib.sign_out(pg)
    sign_in_ui(pg, 'o@x.com', 'Strong-Pass9')
    lib.poll(pg, "!!document.querySelector('#acMfaDlg')", 5)
    t.check('auth dialog closed, code dialog open', pg.is_hidden('#authDlg') and pg.is_visible('#acMfaDlg'))
    t.check('not signed in for the app yet', pg.is_visible('#signInBtn') and not pg.evaluate('!!Backend.user'))
    t.check('code dialog names the account', 'o@x.com' in pg.inner_text('#acMfaDlgD'))
    pg.fill('#acMfaCode', '111111'); time.sleep(0.6)
    t.check('wrong code → message, still pending', 'הקוד לא התאים' in pg.inner_text('#acMfaMsg') and not pg.evaluate('!!Backend.user'))
    pg.fill('#acMfaCode', '123456'); time.sleep(0.8)
    t.check('right code → signed in', pg.evaluate('!!Backend.user') and pg.is_visible('#accBtn') and pg.query_selector('#acMfaDlg') is None)
    lib.sign_out(pg)
    sign_in_ui(pg, 'o@x.com', 'Strong-Pass9'); lib.poll(pg, "!!document.querySelector('#acMfaDlg')", 5)
    pg.click('#acMfaNo'); time.sleep(0.4)
    t.check('"sign out" from the code step → signed out, dialog gone', pg.query_selector('#acMfaDlg') is None and not pg.evaluate('!!Backend.user'))

    t.section('admin banner without 2FA; admin delete user')
    lib.sign_up(pg, 'oshri2x', 'o2@x.com', 'Strong-Pass9')
    pg.evaluate("__mock.setProfile({role:'admin'})"); pg.evaluate("Backend.signOut()"); time.sleep(0.3); lib.sign_in(pg, 'o2@x.com', 'Strong-Pass9'); time.sleep(0.8)
    pg.click('#adminBtn'); lib.poll(pg, "document.querySelector('#acMfaBan')&&!document.querySelector('#acMfaBan').hidden", 6)
    t.check('banner urges 2FA (he)', 'אימות דו־שלבי' in pg.inner_text('#acMfaBan'), pg.inner_text('#acMfaBan'))
    pg.evaluate("[...document.querySelectorAll('#uBody tr')].find(tr=>tr.textContent.includes('dana_beats')).querySelector('.acts .btn').click()"); time.sleep(0.8)
    t.check('"Delete user" in the user details', pg.is_visible('#acUdDel'), pg.evaluate("document.querySelector('#acUdDelW')&&document.querySelector('#acUdDelW').outerHTML.slice(0,200)"))
    pg.click('#acUdDel'); time.sleep(0.3)
    pg.fill('#acUdConf', 'wrong'); pg.click('#acUdGo'); time.sleep(0.3)
    t.check('wrong confirmation refused', 'האישור לא תואם' in pg.inner_text('#acUdMsg'))
    pg.fill('#acUdConf', 'dana_beats'); pg.click('#acUdGo'); time.sleep(1)
    t.check('user deleted', 'u0' in (pg.evaluate('window.__deleted') or []) and pg.query_selector('#acUdDlg') is None)
    t.check('audit row', pg.evaluate("(window.__log||[]).some(x=>x.action==='adm_delete_user')"))
    o2 = pg.evaluate("__mock.profiles.find(p=>p.username==='oshri').id")
    pg.evaluate(f"__mock.setProfile({{owner:true}},'{o2}')")
    pg.evaluate(f"(()=>{{const A=CR.ACC;A.admUser={{...(A.users.find(u=>u.id==='{o2}')||{{id:'{o2}'}}),owner:true}};document.querySelector('#udName').textContent='x'+Date.now()}})()"); time.sleep(0.3)
    t.check('no "Delete user" for the owner', pg.evaluate("document.querySelector('#acUdDelW').hidden"))
    pg.click('#adminClose'); time.sleep(0.2)
    t.check('zero CSP violations', lib.csp_violations(pg) == [], lib.csp_violations(pg))
    ctx.close()

    t.section('delete my account (password) + local data cleared')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='en', init=lib.CSP_INIT)
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    lib.sign_in(pg); time.sleep(0.5)
    pg.evaluate("""localStorage.setItem('chordroom.crate.v1:u0','[1]');localStorage.setItem('chordroom.payok.v1:u0','{}');localStorage.setItem('chordroom.mashup.v1:u0','{}');
                   localStorage.setItem('chordroom.crate.v1:u9','[2]');localStorage.setItem('chordroom.payjobs.v1',JSON.stringify([{id:1,uid:'u0',t:Date.now()},{id:2,uid:'u9',t:Date.now()}]));sessionStorage.setItem('chordroom.visit.u0','x')""")
    pg.evaluate("""new Promise(ok=>{const r=indexedDB.open('chordroom',1);r.onupgradeneeded=()=>r.result.createObjectStore('kv');r.onsuccess=()=>{const tx=r.result.transaction('kv','readwrite');
                   tx.objectStore('kv').put({name:'mine',uid:'u0'},'audio');tx.objectStore('kv').put({name:'mine',uid:'u0'},'state');tx.oncomplete=()=>{r.result.close();ok()}}})""")
    open_acc(pg)
    t.eq('danger zone (en)', pg.inner_text('#acDangerH').lower(), 'danger zone')
    pg.click('#acDelBtn'); time.sleep(0.4)
    txt = pg.inner_text('#acDelDlg')
    t.check('explains what is deleted (points, files, browser data, payment records kept)', all(x in txt for x in ['points', 'uploaded files', 'this browser', '7 years']), txt[:300])
    t.check('confirmation label names the username + DELETE', pg.evaluate("(t=>t.includes('@dana_beats')&&t.includes('DELETE'))(document.querySelector('#acDelConfL').textContent)"), pg.evaluate("document.querySelector('#acDelConfL').textContent"))
    t.shot(pg, 'delete_en')
    pg.fill('#acDelConf', 'nope'); pg.fill('#acDelPw', 'password1'); pg.click('#acDelGo'); time.sleep(0.3)
    t.check('confirmation mismatch refused', 'doesn’t match' in pg.inner_text('#acDelMsg'), pg.inner_text('#acDelMsg'))
    pg.fill('#acDelConf', 'DELETE'); pg.fill('#acDelPw', 'wrongpass'); pg.click('#acDelGo'); time.sleep(0.4)
    t.check('wrong password refused', 'Wrong password' in pg.inner_text('#acDelMsg'), pg.inner_text('#acDelMsg'))
    t.check('still signed in', pg.evaluate('!!Backend.user'))
    pg.fill('#acDelPw', 'password1'); pg.click('#acDelGo'); time.sleep(1.2)
    t.check('account deleted', 'u0' in (pg.evaluate('window.__deleted') or []) and not pg.evaluate("__mock.profiles.some(p=>p.id==='u0')"))
    t.check('signed out', not pg.evaluate('!!Backend.user') and pg.is_visible('#signInBtn'))
    t.check('notice dialog', pg.is_visible('#acDelDone') and 'deleted' in pg.inner_text('#acDelDoneH'))
    ls = pg.evaluate("Object.keys(localStorage).filter(k=>k.startsWith('chordroom'))")
    t.check("this account's keys removed", not any(k.endswith(':u0') for k in ls), ls)
    t.check("another account's keys kept", 'chordroom.crate.v1:u9' in ls)
    t.eq('pay journal: only the other account left', pg.evaluate("JSON.parse(localStorage.getItem('chordroom.payjobs.v1')||'[]').map(j=>j.uid)"), ['u9'])
    t.check('session keys removed', pg.evaluate("sessionStorage.getItem('chordroom.visit.u0')") is None)
    t.eq('remembered song removed', pg.evaluate("new Promise(ok=>{const r=indexedDB.open('chordroom',1);r.onsuccess=()=>{const g=r.result.transaction('kv').objectStore('kv').get('audio');g.onsuccess=()=>{ok(g.result||null);r.result.close()}}})"), None)
    pg.click('#acDelDoneOk'); time.sleep(0.4)
    t.check('back on the home page', not pg.is_hidden('#aboutView'))
    t.check('zero CSP violations', lib.csp_violations(pg) == [], lib.csp_violations(pg))
    ctx.close()

    t.section('delete with an e-mail code (he: מחק) + 2FA user + owner / subscription refused')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='he')
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    lib.sign_up(pg, 'mika', 'm@x.com', 'Strong-Pass9')
    open_acc(pg); pg.click('#acDelBtn'); time.sleep(0.3)
    t.check('confirmation label in Hebrew with מחק', 'מחק' in pg.evaluate("document.querySelector('#acDelConfL').textContent"))
    pg.click('#acDelNoPw'); time.sleep(0.2)
    t.check('password field replaced by the code flow', pg.is_hidden('#acDelPwF') and pg.is_visible('#acDelSend'))
    pg.click('#acDelSend'); time.sleep(0.4)
    t.check('code sent', pg.evaluate('window.__reauthMail') == 'm@x.com' and 'שלחנו' in pg.inner_text('#acDelMsg'))
    pg.fill('#acDelConf', 'מחק'); pg.fill('#acDelCode', '123123'); pg.click('#acDelGo'); time.sleep(0.4)
    t.check('wrong e-mail code refused', 'הקוד לא התאים' in pg.inner_text('#acDelMsg'), pg.inner_text('#acDelMsg'))
    pg.fill('#acDelCode', '777777'); pg.click('#acDelGo'); time.sleep(1.2)
    t.eq('deleted with the code + מחק', pg.evaluate('window.__deleteConfirm'), 'מחק')
    lib.close_dialogs(pg); pg.evaluate("document.querySelectorAll('.acwrap').forEach(x=>x.remove())")
    lib.sign_up(pg, 'tfa_user', 't@x.com', 'Strong-Pass9')
    pg.evaluate("__mock.addFactor(Backend.user.id)")
    open_acc(pg); pg.click('#acDelBtn'); time.sleep(0.4)
    t.check('2FA account: authenticator code field', pg.is_visible('#acDelTotp'))
    pg.fill('#acDelConf', 'tfa_user'); pg.fill('#acDelPw', 'Strong-Pass9'); pg.click('#acDelGo'); time.sleep(0.3)
    t.check('code required', 'הקוד מאפליקציית האימות' in pg.inner_text('#acDelMsg'), pg.inner_text('#acDelMsg'))
    pg.fill('#acDelTotp', '123456'); pg.click('#acDelGo'); time.sleep(1.2)
    t.check('2FA account deleted after password + code', pg.evaluate("(window.__deleted||[]).length") == 2)
    lib.close_dialogs(pg); pg.evaluate("document.querySelectorAll('.acwrap').forEach(x=>x.remove())")
    lib.sign_up(pg, 'boss', 'b@x.com', 'Strong-Pass9'); pg.evaluate("__mock.setProfile({owner:true})")
    open_acc(pg); pg.click('#acDelBtn'); time.sleep(0.6)
    t.check('owner: explained, no form', 'בעל האתר' in pg.inner_text('#acDelDlg') and pg.is_hidden('#acDelF'))
    pg.keyboard.press('Escape'); time.sleep(0.2)
    t.check('Esc closes the dialog', pg.query_selector('#acDelDlg') is None)
    pg.evaluate("__mock.setProfile({owner:false,pay_status:'active',pay_portal:'https://store.lemonsqueezy.com/billing?x=1'})")
    pg.click('#acDelBtn'); time.sleep(0.6)
    t.check('live subscription: explained + portal link, no form', 'מנוי פעיל' in pg.inner_text('#acDelDlg') and pg.is_hidden('#acDelF')
            and pg.evaluate("document.querySelector('#acDelPortal').href").startswith('https://store.lemonsqueezy.com/'))
    pg.keyboard.press('Escape'); time.sleep(0.2)
    t.section('sign out of all devices')
    pg.click('#acOutAll'); time.sleep(0.6)
    t.check('global sign-out called + signed out', pg.evaluate('window.__signOutAll') == 1 and not pg.evaluate('!!Backend.user'))
    ctx.close()

    t.section('Turnstile: no site key → nothing loads')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='en', init=lib.CSP_INIT)
    ts_route(ctx)
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    pg.click('#signInBtn'); time.sleep(0.6)
    t.check('no Turnstile script', pg.evaluate("![...document.scripts].some(s=>s.src.includes('challenges.cloudflare.com'))"))
    t.check('no widget slot shown', pg.evaluate("!document.querySelector('#acCapAu')||document.querySelector('#acCapAu').hidden||!document.querySelector('#acCapAu').children.length"))
    pg.fill('#inEmail', 'dana@example.com'); pg.fill('#inPass', 'password1'); pg.click('#fIn .au-cta'); time.sleep(0.8)
    t.check('sign-in works without a token', pg.evaluate('!!Backend.user') and pg.evaluate('window.__captcha.at(-1).tok') is None)
    ctx.close()

    t.section('Turnstile: site key → widget + tokens (ar, dark)')
    KEY = '0x4AAAAAAATestSiteKey01'
    ctx, pg = lib.page(b, srv, t, mock=mock_with({'turnstile_site_key': KEY}), lang='ar', theme='dark', init=lib.CSP_INIT)
    ts_route(ctx)
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    pg.click('#signInBtn'); lib.poll(pg, "window.__tsRenders>0", 8)
    t.check('Turnstile api.js loaded (explicit render)', pg.evaluate("[...document.scripts].some(s=>s.src.startsWith('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'))"))
    t.check('widget rendered inside the auth dialog', pg.evaluate("!!document.querySelector('#authDlg #acCapAu .cf-stub')"))
    t.eq('widget options: dark theme, Arabic, interaction-only', pg.evaluate("[__tsOpts.theme,__tsOpts.language,__tsOpts.appearance,__tsOpts.sitekey]"), ['dark', 'ar', 'interaction-only', KEY])
    t.eq('slot labelled (ar)', pg.get_attribute('#acCapAu', 'aria-label'), 'فحص أمني')
    t.shot(pg, 'turnstile_ar_dark')
    pg.fill('#inEmail', 'dana@example.com'); pg.fill('#inPass', 'password1'); pg.click('#fIn .au-cta'); lib.poll(pg, '!!Backend.user', 8)
    t.check('sign-in sent a token', str(pg.evaluate('window.__captcha.at(-1).tok') or '').startswith('tok-'), pg.evaluate('window.__captcha'))
    lib.sign_out(pg)
    pg.evaluate("window.__captchaRequired=true;window.__tsFail=true;ACCT._cap.w.forEach(s=>{s.token='';turnstile.reset(s.id)})"); time.sleep(0.3)
    pg.click('#signInBtn'); time.sleep(0.5); pg.fill('#inEmail', 'dana@example.com'); pg.fill('#inPass', 'password1'); pg.click('#fIn .au-cta'); time.sleep(1.2)
    t.check('failed check → message, not signed in', not pg.evaluate('!!Backend.user') and 'الفحص الأمني' in pg.inner_text('#auMsg'), pg.inner_text('#auMsg'))
    pg.evaluate("window.__tsFail=false;ACCT._cap.w.forEach(s=>turnstile.reset(s.id))"); time.sleep(0.3)
    pg.click('#toForgot'); time.sleep(0.3); pg.fill('#fgEmail', 'dana@example.com'); pg.click('#fForgot .au-cta'); time.sleep(1)
    t.check('password reset sent a token', any(x['a'] == 'reset' and str(x['tok'] or '').startswith('tok-') for x in pg.evaluate('window.__captcha')), pg.evaluate('window.__captcha'))
    t.eq('page RTL in Arabic', pg.evaluate('document.documentElement.dir'), 'rtl')
    t.check('zero CSP violations with Turnstile', lib.csp_violations(pg) == [], lib.csp_violations(pg))
    ctx.close()

    t.section('idle sign-out (fake clock)')
    ctx = lib.context(b, srv, mock=mock_with({'idle_minutes': 30, 'idle_minutes_admin': 20}), lang='en')
    pg = ctx.new_page(); lib.watch(pg, t.errs)
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    lib.need(pg, 'acct')   # perf merge: acct.js loads on first use (sign-in / auth dialog / saved session); a guest page has it after need()
    pg.evaluate("window.__T=Date.now();ACCT._idle.setNow(()=>window.__T)")
    lib.sign_in(pg); time.sleep(0.3)
    t.eq('user limit from billing.idle_minutes', pg.evaluate('ACCT._idle.limit()'), 30 * 60000)
    pg.evaluate("window.__T+=28*60000;ACCT._idle.tick()"); time.sleep(0.2)
    t.check('no warning 2 min before', pg.query_selector('#acIdleDlg') is None)
    pg.evaluate("window.__T+=90000;ACCT._idle.tick()"); time.sleep(0.2)
    t.check('warning 30 s before the limit', pg.is_visible('#acIdleDlg') and 'signed out in' in pg.inner_text('#acIdleDlgD'), pg.inner_text('#acIdleDlg') if pg.query_selector('#acIdleDlg') else '')
    t.eq('warning is an alertdialog with focus on "stay"', pg.evaluate("[document.querySelector('#acIdleDlg .dlg').getAttribute('role'),document.activeElement.id]"), ['alertdialog', 'acIdleStay'])
    t.shot(pg, 'idle_warn')
    pg.click('#acIdleStay'); time.sleep(0.2)
    t.check('"stay signed in" closes it', pg.query_selector('#acIdleDlg') is None and pg.evaluate('!!Backend.user'))
    pg2 = ctx.new_page(); lib.watch(pg2, t.errs); pg2.goto(srv.url('#tool')); lib.wait_booted(pg2); lib.need(pg2, 'acct')
    pg.evaluate("window.__T+=29*60000+40000;")
    pg2.evaluate(f"window.__T={pg.evaluate('window.__T')};ACCT._idle.setNow(()=>window.__T)"); lib.sign_in(pg2); time.sleep(0.3)
    pg2.evaluate("ACCT._idle.touch()"); time.sleep(0.3)
    pg.evaluate("ACCT._idle.tick()"); time.sleep(0.2)
    t.check('activity in another tab resets this one', pg.query_selector('#acIdleDlg') is None and pg.evaluate('!!Backend.user'))
    pg2.close()
    pg.evaluate("window.__T+=31*60000;ACCT._idle.tick()"); time.sleep(0.6)
    t.check('past the limit → signed out + notice', not pg.evaluate('!!Backend.user') and 'inactivity' in pg.inner_text('#toast'), pg.inner_text('#toast'))
    lib.sign_up(pg, 'oshri', 'o@x.com', 'Strong-Pass9'); time.sleep(0.8)
    t.eq('admin-panel account: billing.idle_minutes_admin', pg.evaluate('ACCT._idle.limit()'), 20 * 60000)
    pg.evaluate("window.__T+=19*60000+30000;ACCT._idle.tick()"); time.sleep(0.2)
    t.check('admin warning before 20 min', pg.is_visible('#acIdleDlg'))
    pg.click('#acIdleOut'); time.sleep(0.5)
    t.check('"sign out now" signs out', not pg.evaluate('!!Backend.user') and pg.query_selector('#acIdleDlg') is None)
    ctx.close()

    t.section('offensive words: browser = SQL, profile + sign-up refused, age checkbox')
    ctx, pg = lib.page(b, srv, t, mock=mock_with({'min_age': 18}), lang='he', init=lib.CSP_INIT)
    pg.goto(srv.url('#tool')); lib.wait_booted(pg); lib.need(pg, 'acct')   # TEXTGUARD / CR.offensive come with acct.js
    res = pg.evaluate("a=>a.map(s=>TEXTGUARD.offensive(s))", OFFENSIVE)
    t.check(f'all {len(OFFENSIVE)} offensive cases flagged in the browser', all(res), [s for s, r in zip(OFFENSIVE, res) if not r])
    res = pg.evaluate("a=>a.map(s=>TEXTGUARD.offensive(s))", CLEAN)
    t.check(f'no false positive on {len(CLEAN)} common words', not any(res), [s for s, r in zip(CLEAN, res) if r])
    t.check('CR.offensive is the shared helper', pg.evaluate("CR.offensive('sh1t')===true&&CR.offensive('Scunthorpe')===false"))
    pg.click('#signUpBtn'); time.sleep(0.4)
    pg.fill('#upUser', 'fuck_off'); time.sleep(0.6)
    t.check('offensive username refused at sign-up (he)', 'אסור' in pg.inner_text('#upUserS'), pg.inner_text('#upUserS'))
    pg.fill('#upUser', 'nice_dj'); pg.fill('#upEmail', 'n@x.com'); pg.fill('#upPass', 'Strong-Pass9x'); pg.fill('#upPass2', 'Strong-Pass9x'); time.sleep(0.6); pg.click('#fUp .au-cta'); time.sleep(0.6)
    t.check('terms step', pg.is_visible('#fTerms'))
    t.eq('age label follows billing.min_age', pg.evaluate("document.querySelector('#auAge').parentElement.querySelector('[data-acage]').textContent"), 'אני בן/בת 18 ומעלה')
    pg.check('#auAgree'); time.sleep(0.1)
    t.check('create disabled without the age box', pg.is_disabled('#auCreate'))
    pg.check('#auAge'); time.sleep(0.1)
    t.check('both boxes → enabled', not pg.is_disabled('#auCreate'))
    pg.click('#auCreate'); lib.poll(pg, '!!Backend.user', 6)
    meta = pg.evaluate('window.__signupMeta')
    t.check('age consent sent with the sign-up (ok, min 18)', meta and meta['age'] and meta['age']['ok'] is True and meta['age']['min'] == 18, meta)
    lib.close_dialogs(pg)
    open_acc(pg)
    pg.fill('#pUname', 'sh1t_lord'); pg.click('#pSave'); time.sleep(0.4)
    t.check('profile: offensive username refused instantly', 'אסור' in pg.inner_text('#pMsg') and pg.evaluate("__mock.profiles.find(p=>p.id===Backend.user.id).username") == 'nice_dj', pg.inner_text('#pMsg'))
    pg.fill('#pUname', 'nice_dj'); pg.fill('#pBio', 'אני שַׁרְמוּטָה'); pg.click('#pSave'); time.sleep(0.4)
    t.check('profile: offensive bio refused', 'אסורות' in pg.inner_text('#pMsg'), pg.inner_text('#pMsg'))
    pg.fill('#pBio', 'DJ from Scunthorpe, cocktails & bass'); pg.click('#pSave'); time.sleep(0.6)
    t.check('profile: clean text saved', pg.evaluate("__mock.profiles.find(p=>p.id===Backend.user.id).bio").startswith('DJ from Scunthorpe'))
    pg.select_option('#lang', 'en'); time.sleep(0.4)
    t.eq('language flip: 2FA heading in English', pg.text_content('#acMfaH'), 'Two-step verification (2FA)')
    for L, word in [('ar', 'منطقة خطرة'), ('ru', 'Опасная зона'), ('es', 'Zona de peligro')]:
        pg.select_option('#lang', L); time.sleep(0.3)
        t.check(f'danger zone heading ({L})', word.lower() in pg.inner_text('#acDangerH').lower(), pg.inner_text('#acDangerH'))
    t.check('zero CSP violations', lib.csp_violations(pg) == [], lib.csp_violations(pg))
    ctx.close()

    t.section('admin Settings → Security + blocked words')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='en')
    pg.goto(srv.url('#tool')); lib.wait_booted(pg)
    lib.sign_up(pg, 'oshri', 'o@x.com', 'Strong-Pass9'); pg.evaluate("__mock.setProfile({owner:true})"); pg.evaluate("Backend.signOut()"); time.sleep(0.3); lib.sign_in(pg, 'o@x.com', 'Strong-Pass9'); time.sleep(0.8)
    pg.click('#adminBtn'); time.sleep(0.5); pg.click('#admTabs [data-v="settings"]'); time.sleep(0.6)
    t.check('security block visible', pg.is_visible('#acSec') and pg.inner_text('#acSecH').lower() == 'security')
    t.eq('defaults: idle 10080 / 60, min age 16', [pg.input_value('#acIdleU'), pg.input_value('#acIdleA'), pg.input_value('#acAgeMin')], ['10080', '60', '16'])
    t.check('owner may switch "2FA for management"', not pg.is_disabled('#acReq'))
    pg.fill('#acTs', 'javascript:alert(1)'); pg.click('#acSecSave'); time.sleep(0.3)
    t.check('bad Turnstile key refused in the form', 'err' in (pg.get_attribute('#acSecMsg', 'class') or ''))
    pg.fill('#acTs', '0x4AAAAAAATestSiteKey01'); pg.fill('#acIdleA', '45'); pg.check('#acReq'); pg.click('#acSecSave'); time.sleep(0.5)
    cfgb = pg.evaluate('__mock.cfg.billing')
    t.check('saved to billing', cfgb.get('turnstile_site_key') == '0x4AAAAAAATestSiteKey01' and cfgb.get('idle_minutes_admin') == 45 and cfgb.get('require_mfa_admin') is True, cfgb)
    lib.poll(pg, "document.querySelectorAll('#acWordList li').length>=2", 5)
    pg.fill('#acWord', 'Banana'); pg.click('#acWordAdd'); time.sleep(0.5)
    t.check('word added to the list', 'banana' in pg.inner_text('#acWordList'))
    t.check('…and refused in profile text at once (server answer)', pg.evaluate("Backend.textOk('my banana')") is False)
    pg.click('#acWordList li:last-child .acwx'); time.sleep(0.5)
    t.check('word removed', 'banana' not in pg.inner_text('#acWordList'))
    t.check('remove buttons are labelled', pg.get_attribute('#acWordList li .acwx', 'aria-label').startswith('Remove '))
    t.shot(pg, 'admin_security')
    pg.evaluate("__mock.setProfile({owner:false})"); pg.evaluate("CR.ACC.owner=false"); pg.click('#admTabs [data-v="users"]'); time.sleep(0.2); pg.click('#admTabs [data-v="settings"]'); time.sleep(0.4)
    t.check('a full admin (not owner) cannot switch "2FA for management"', pg.is_disabled('#acReq'))
    ctx.close()

    t.section('client brake after 5 wrong passwords')
    ctx, pg = lib.page(b, srv, t, mock=True, lang='en')
    pg.goto(srv.url('#tool')); lib.wait_booted(pg); lib.need(pg, 'acct')   # the brake wraps Backend.signIn when acct.js loads (the auth dialog loads it)
    codes = pg.evaluate("""async()=>{const out=[];for(let i=0;i<6;i++){try{await Backend.signIn({email:'dana@example.com',password:'bad'+i})}catch(e){out.push(e.code+(e.wait?':'+e.wait:''))}}return out}""")
    t.check('5 × login, then rate with a wait', codes[:5] == ['login'] * 5 and codes[5].startswith('rate:'), codes)
    ctx.close()

    t.section('mobile 375: he light + ar dark (no horizontal scroll, dialogs fit)')
    for lang, theme in [('he', 'light'), ('ar', 'dark')]:
        ctx, pg = lib.page(b, srv, t, mock=True, lang=lang, theme=theme, w=375, h=760, mobile=True, init=lib.CSP_INIT)
        pg.goto(srv.url('#tool')); lib.wait_booted(pg)
        lib.sign_in(pg); time.sleep(0.5)
        pg.click('#accBtn'); lib.poll(pg, "!!document.querySelector('#acDelBtn')", 5); time.sleep(0.4)
        pg.evaluate("document.querySelector('#acDanger').scrollIntoView()"); time.sleep(0.2)
        t.check(f'{lang}: account panel fits 375', lib.scroll_width(pg) == 375, lib.scroll_width(pg))
        pg.click('#acDelBtn'); time.sleep(0.4)
        r = lib.rect(pg, '#acDelDlg .dlg')
        t.check(f'{lang}: delete dialog inside the viewport', r['l'] >= 0 and r['r'] <= 375, r)
        t.check(f'{lang}: no horizontal scroll with the dialog', lib.scroll_width(pg) == 375)
        t.eq(f'{lang}: RTL', pg.evaluate('document.documentElement.dir'), 'rtl')
        if theme == 'dark':
            t.check('ar dark: dialog surface is dark', lib.page_luma(pg, '#acDelDlg .dlg') < 60, lib.page_luma(pg, '#acDelDlg .dlg'))
            t.check('ar dark: danger button readable', pg.evaluate("(()=>{const s=getComputedStyle(document.querySelector('#acDelGo'));return s.color!==s.backgroundColor})()"))
        t.shot(pg, f'delete_{lang}_{theme}_375')
        pg.keyboard.press('Escape'); time.sleep(0.2)
        pg.click('#acMfaOn'); lib.poll(pg, "document.querySelector('#acEnr img')", 5)
        r = lib.rect(pg, '#acEnr .dlg')
        t.check(f'{lang}: 2FA dialog fits 375', r['l'] >= 0 and r['r'] <= 375 and lib.scroll_width(pg) == 375, r)
        t.check(f'{lang}: zero CSP violations', lib.csp_violations(pg) == [], lib.csp_violations(pg))
        ctx.close()
